import flags from "react-phone-number-input/flags";

export const userRoles = {
  ADMIN: "admin",
  MANAGER: "manager",
  ASSOCIATE: "associate",
};

export const authorizeStatus = ["active", "approved"];

export const countries = [
  {
    alpha2: "AD",
    alpha3: "AND",
    countryCallingCodes: ["376"],
    currencies: ["EUR"],
    emoji: "ðŸ‡¦ðŸ‡©",
    ioc: "AND",
    languages: ["cat"],
    name: "Andorra",
    status: "assigned",
  },
  {
    alpha2: "AE",
    alpha3: "ARE",
    countryCallingCodes: ["971"],
    currencies: ["AED"],
    emoji: "ðŸ‡¦ðŸ‡ª",
    ioc: "UAE",
    languages: ["ara"],
    name: "United Arab Emirates",
    status: "assigned",
  },
  {
    alpha2: "AF",
    alpha3: "AFG",
    countryCallingCodes: ["93"],
    currencies: ["AFN"],
    emoji: "ðŸ‡¦ðŸ‡«",
    ioc: "AFG",
    languages: ["pus"],
    name: "Afghanistan",
    status: "assigned",
  },
  {
    alpha2: "AG",
    alpha3: "ATG",
    countryCallingCodes: ["1 268"],
    currencies: ["XCD"],
    emoji: "ðŸ‡¦ðŸ‡¬",
    ioc: "ANT",
    languages: ["eng"],
    name: "Antigua And Barbuda",
    status: "assigned",
  },
  {
    alpha2: "AI",
    alpha3: "AIA",
    countryCallingCodes: ["1 264"],
    currencies: ["XCD"],
    emoji: "ðŸ‡¦ðŸ‡®",
    ioc: "",
    languages: ["eng"],
    name: "Anguilla",
    status: "assigned",
  },
  {
    alpha2: "AI",
    alpha3: "AFI",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "French Afar and Issas",
    status: "deleted",
  },
  {
    alpha2: "AL",
    alpha3: "ALB",
    countryCallingCodes: ["355"],
    currencies: ["ALL"],
    emoji: "ðŸ‡¦ðŸ‡±",
    ioc: "ALB",
    languages: ["sqi"],
    name: "Albania",
    status: "assigned",
  },
  {
    alpha2: "AM",
    alpha3: "ARM",
    countryCallingCodes: ["374"],
    currencies: ["AMD"],
    emoji: "ðŸ‡¦ðŸ‡²",
    ioc: "ARM",
    languages: ["hye", "rus"],
    name: "Armenia",
    status: "assigned",
  },
  {
    alpha2: "AN",
    alpha3: "ANT",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "Netherlands Antilles",
    status: "deleted",
  },
  {
    alpha2: "AO",
    alpha3: "AGO",
    countryCallingCodes: ["244"],
    currencies: ["AOA"],
    emoji: "ðŸ‡¦ðŸ‡´",
    ioc: "ANG",
    languages: ["por"],
    name: "Angola",
    status: "assigned",
  },
  {
    alpha2: "AQ",
    alpha3: "ATA",
    countryCallingCodes: ["672"],
    currencies: [],
    emoji: "ðŸ‡¦ðŸ‡¶",
    ioc: "",
    languages: [],
    name: "Antarctica",
    status: "assigned",
  },
  {
    alpha2: "AR",
    alpha3: "ARG",
    countryCallingCodes: ["54"],
    currencies: ["ARS"],
    emoji: "ðŸ‡¦ðŸ‡·",
    ioc: "ARG",
    languages: ["spa"],
    name: "Argentina",
    status: "assigned",
  },
  {
    alpha2: "AS",
    alpha3: "ASM",
    countryCallingCodes: ["1 684"],
    currencies: ["USD"],
    emoji: "ðŸ‡¦ðŸ‡¸",
    ioc: "ASA",
    languages: ["eng", "smo"],
    name: "American Samoa",
    status: "assigned",
  },
  {
    alpha2: "AT",
    alpha3: "AUT",
    countryCallingCodes: ["43"],
    currencies: ["EUR"],
    emoji: "ðŸ‡¦ðŸ‡¹",
    ioc: "AUT",
    languages: ["deu"],
    name: "Austria",
    status: "assigned",
  },
  {
    alpha2: "AU",
    alpha3: "AUS",
    countryCallingCodes: ["61"],
    currencies: ["AUD"],
    emoji: "ðŸ‡¦ðŸ‡º",
    ioc: "AUS",
    languages: ["eng"],
    name: "Australia",
    status: "assigned",
  },
  {
    alpha2: "AW",
    alpha3: "ABW",
    countryCallingCodes: ["297"],
    currencies: ["AWG"],
    emoji: "ðŸ‡¦ðŸ‡¼",
    ioc: "ARU",
    languages: ["nld"],
    name: "Aruba",
    status: "assigned",
  },
  {
    alpha2: "AX",
    alpha3: "ALA",
    countryCallingCodes: ["358"],
    currencies: ["EUR"],
    emoji: "ðŸ‡¦ðŸ‡½",
    ioc: "",
    languages: ["swe"],
    name: "Ã…land Islands",
    status: "assigned",
  },
  {
    alpha2: "AZ",
    alpha3: "AZE",
    countryCallingCodes: ["994"],
    currencies: ["AZN"],
    emoji: "ðŸ‡¦ðŸ‡¿",
    ioc: "AZE",
    languages: ["aze"],
    name: "Azerbaijan",
    status: "assigned",
  },
  {
    alpha2: "BA",
    alpha3: "BIH",
    countryCallingCodes: ["387"],
    currencies: ["BAM"],
    emoji: "ðŸ‡§ðŸ‡¦",
    ioc: "BIH",
    languages: ["bos", "cre", "srp"],
    name: "Bosnia & Herzegovina",
    status: "assigned",
  },
  {
    alpha2: "BB",
    alpha3: "BRB",
    countryCallingCodes: ["1 246"],
    currencies: ["BBD"],
    emoji: "ðŸ‡§ðŸ‡§",
    ioc: "BAR",
    languages: ["eng"],
    name: "Barbados",
    status: "assigned",
  },
  {
    alpha2: "BD",
    alpha3: "BGD",
    countryCallingCodes: ["880"],
    currencies: ["BDT"],
    emoji: "ðŸ‡§ðŸ‡©",
    ioc: "BAN",
    languages: ["ben"],
    name: "Bangladesh",
    status: "assigned",
  },
  {
    alpha2: "BE",
    alpha3: "BEL",
    countryCallingCodes: ["32"],
    currencies: ["EUR"],
    emoji: "ðŸ‡§ðŸ‡ª",
    ioc: "BEL",
    languages: ["nld", "fra", "deu"],
    name: "Belgium",
    status: "assigned",
  },
  {
    alpha2: "BF",
    alpha3: "BFA",
    countryCallingCodes: ["226"],
    currencies: ["XOF"],
    emoji: "ðŸ‡§ðŸ‡«",
    ioc: "BUR",
    languages: ["fra"],
    name: "Burkina Faso",
    status: "assigned",
  },
  {
    alpha2: "BG",
    alpha3: "BGR",
    countryCallingCodes: ["359"],
    currencies: ["BGN"],
    emoji: "ðŸ‡§ðŸ‡¬",
    ioc: "BUL",
    languages: ["bul"],
    name: "Bulgaria",
    status: "assigned",
  },
  {
    alpha2: "BH",
    alpha3: "BHR",
    countryCallingCodes: ["973"],
    currencies: ["BHD"],
    emoji: "ðŸ‡§ðŸ‡­",
    ioc: "BRN",
    languages: ["ara"],
    name: "Bahrain",
    status: "assigned",
  },
  {
    alpha2: "BI",
    alpha3: "BDI",
    countryCallingCodes: ["257"],
    currencies: ["BIF"],
    emoji: "ðŸ‡§ðŸ‡®",
    ioc: "BDI",
    languages: ["fra"],
    name: "Burundi",
    status: "assigned",
  },
  {
    alpha2: "BJ",
    alpha3: "BEN",
    countryCallingCodes: ["229"],
    currencies: ["XOF"],
    emoji: "ðŸ‡§ðŸ‡¯",
    ioc: "BEN",
    languages: ["fra"],
    name: "Benin",
    status: "assigned",
  },
  {
    alpha2: "BL",
    alpha3: "BLM",
    countryCallingCodes: ["590"],
    currencies: ["EUR"],
    emoji: "ðŸ‡§ðŸ‡±",
    ioc: "",
    languages: ["fra"],
    name: "Saint BarthÃ©lemy",
    status: "assigned",
  },
  {
    alpha2: "BM",
    alpha3: "BMU",
    countryCallingCodes: ["1 441"],
    currencies: ["BMD"],
    emoji: "ðŸ‡§ðŸ‡²",
    ioc: "BER",
    languages: ["eng"],
    name: "Bermuda",
    status: "assigned",
  },
  {
    alpha2: "BN",
    alpha3: "BRN",
    countryCallingCodes: ["673"],
    currencies: ["BND"],
    emoji: "ðŸ‡§ðŸ‡³",
    ioc: "BRU",
    languages: ["msa", "eng"],
    name: "Brunei Darussalam",
    status: "assigned",
  },
  {
    alpha2: "BO",
    alpha3: "BOL",
    countryCallingCodes: ["591"],
    currencies: ["BOB", "BOV"],
    emoji: "ðŸ‡§ðŸ‡´",
    ioc: "BOL",
    languages: ["spa", "aym", "que"],
    name: "Bolivia, Plurinational State Of",
    status: "assigned",
  },
  {
    alpha2: "BQ",
    alpha3: "BES",
    countryCallingCodes: ["599"],
    currencies: ["USD"],
    emoji: "ðŸ‡§ðŸ‡¶",
    ioc: "",
    languages: ["nld"],
    name: "Bonaire, Saint Eustatius And Saba",
    status: "assigned",
  },
  {
    alpha2: "BQ",
    alpha3: "ATB",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "British Antarctic Territory",
    status: "deleted",
  },
  {
    alpha2: "BR",
    alpha3: "BRA",
    countryCallingCodes: ["55"],
    currencies: ["BRL"],
    emoji: "ðŸ‡§ðŸ‡·",
    ioc: "BRA",
    languages: ["por"],
    name: "Brazil",
    status: "assigned",
  },
  {
    alpha2: "BS",
    alpha3: "BHS",
    countryCallingCodes: ["1 242"],
    currencies: ["BSD"],
    emoji: "ðŸ‡§ðŸ‡¸",
    ioc: "BAH",
    languages: ["eng"],
    name: "Bahamas",
    status: "assigned",
  },
  {
    alpha2: "BT",
    alpha3: "BTN",
    countryCallingCodes: ["975"],
    currencies: ["INR", "BTN"],
    emoji: "ðŸ‡§ðŸ‡¹",
    ioc: "BHU",
    languages: ["dzo"],
    name: "Bhutan",
    status: "assigned",
  },
  {
    alpha2: "BU",
    alpha3: "BUR",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "Burma",
    status: "deleted",
  },
  {
    alpha2: "BV",
    alpha3: "BVT",
    countryCallingCodes: [],
    currencies: ["NOK"],
    emoji: "ðŸ‡§ðŸ‡»",
    ioc: "",
    languages: [],
    name: "Bouvet Island",
    status: "assigned",
  },
  {
    alpha2: "BW",
    alpha3: "BWA",
    countryCallingCodes: ["267"],
    currencies: ["BWP"],
    emoji: "ðŸ‡§ðŸ‡¼",
    ioc: "BOT",
    languages: ["eng", "tsn"],
    name: "Botswana",
    status: "assigned",
  },
  {
    alpha2: "BY",
    alpha3: "BLR",
    countryCallingCodes: ["375"],
    currencies: ["BYR"],
    emoji: "ðŸ‡§ðŸ‡¾",
    ioc: "BLR",
    languages: ["bel", "rus"],
    name: "Belarus",
    status: "assigned",
  },
  {
    alpha2: "BY",
    alpha3: "BYS",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "Byelorussian SSR",
    status: "deleted",
  },
  {
    alpha2: "BZ",
    alpha3: "BLZ",
    countryCallingCodes: ["501"],
    currencies: ["BZD"],
    emoji: "ðŸ‡§ðŸ‡¿",
    ioc: "BIZ",
    languages: ["eng"],
    name: "Belize",
    status: "assigned",
  },
  {
    alpha2: "CA",
    alpha3: "CAN",
    countryCallingCodes: ["1"],
    currencies: ["CAD"],
    emoji: "ðŸ‡¨ðŸ‡¦",
    ioc: "CAN",
    languages: ["eng", "fra"],
    name: "Canada",
    status: "assigned",
  },
  {
    alpha2: "CC",
    alpha3: "CCK",
    countryCallingCodes: ["61"],
    currencies: ["AUD"],
    emoji: "ðŸ‡¨ðŸ‡¨",
    ioc: "",
    languages: ["eng"],
    name: "Cocos (Keeling) Islands",
    status: "assigned",
  },
  {
    alpha2: "CD",
    alpha3: "COD",
    countryCallingCodes: ["243"],
    currencies: ["CDF"],
    emoji: "ðŸ‡¨ðŸ‡©",
    ioc: "COD",
    languages: ["fra", "lin", "kon", "swa"],
    name: "Democratic Republic Of Congo",
    status: "assigned",
  },
  {
    alpha2: "CF",
    alpha3: "CAF",
    countryCallingCodes: ["236"],
    currencies: ["XAF"],
    emoji: "ðŸ‡¨ðŸ‡«",
    ioc: "CAF",
    languages: ["fra", "sag"],
    name: "Central African Republic",
    status: "assigned",
  },
  {
    alpha2: "CG",
    alpha3: "COG",
    countryCallingCodes: ["242"],
    currencies: ["XAF"],
    emoji: "ðŸ‡¨ðŸ‡¬",
    ioc: "CGO",
    languages: ["fra", "lin"],
    name: "Republic Of Congo",
    status: "assigned",
  },
  {
    alpha2: "CH",
    alpha3: "CHE",
    countryCallingCodes: ["41"],
    currencies: ["CHF", "CHE", "CHW"],
    emoji: "ðŸ‡¨ðŸ‡­",
    ioc: "SUI",
    languages: ["deu", "fra", "ita", "roh"],
    name: "Switzerland",
    status: "assigned",
  },
  {
    alpha2: "CI",
    alpha3: "CIV",
    countryCallingCodes: ["225"],
    currencies: ["XOF"],
    emoji: "ðŸ‡¨ðŸ‡®",
    ioc: "CIV",
    languages: ["fra"],
    name: "CÃ´te d'Ivoire",
    status: "assigned",
  },
  {
    alpha2: "CK",
    alpha3: "COK",
    countryCallingCodes: ["682"],
    currencies: ["NZD"],
    emoji: "ðŸ‡¨ðŸ‡°",
    ioc: "COK",
    languages: ["eng", "mri"],
    name: "Cook Islands",
    status: "assigned",
  },
  {
    alpha2: "CL",
    alpha3: "CHL",
    countryCallingCodes: ["56"],
    currencies: ["CLP", "CLF"],
    emoji: "ðŸ‡¨ðŸ‡±",
    ioc: "CHI",
    languages: ["spa"],
    name: "Chile",
    status: "assigned",
  },
  {
    alpha2: "CM",
    alpha3: "CMR",
    countryCallingCodes: ["237"],
    currencies: ["XAF"],
    emoji: "ðŸ‡¨ðŸ‡²",
    ioc: "CMR",
    languages: ["eng", "fra"],
    name: "Cameroon",
    status: "assigned",
  },
  {
    alpha2: "CN",
    alpha3: "CHN",
    countryCallingCodes: ["86"],
    currencies: ["CNY"],
    emoji: "ðŸ‡¨ðŸ‡³",
    ioc: "CHN",
    languages: ["zho"],
    name: "China",
    status: "assigned",
  },
  {
    alpha2: "CO",
    alpha3: "COL",
    countryCallingCodes: ["57"],
    currencies: ["COP", "COU"],
    emoji: "ðŸ‡¨ðŸ‡´",
    ioc: "COL",
    languages: ["spa"],
    name: "Colombia",
    status: "assigned",
  },
  {
    alpha2: "CR",
    alpha3: "CRI",
    countryCallingCodes: ["506"],
    currencies: ["CRC"],
    emoji: "ðŸ‡¨ðŸ‡·",
    ioc: "CRC",
    languages: ["spa"],
    name: "Costa Rica",
    status: "assigned",
  },
  {
    alpha2: "CS",
    alpha3: "CSK",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "Czechoslovakia",
    status: "deleted",
  },
  {
    alpha2: "CS",
    alpha3: "SCG",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "Serbia and Montenegro",
    status: "deleted",
  },
  {
    alpha2: "CT",
    alpha3: "CTE",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "Canton and Enderbury Islands",
    status: "deleted",
  },
  {
    alpha2: "CU",
    alpha3: "CUB",
    countryCallingCodes: ["53"],
    currencies: ["CUP", "CUC"],
    emoji: "ðŸ‡¨ðŸ‡º",
    ioc: "CUB",
    languages: ["spa"],
    name: "Cuba",
    status: "assigned",
  },
  {
    alpha2: "CV",
    alpha3: "CPV",
    countryCallingCodes: ["238"],
    currencies: ["CVE"],
    emoji: "ðŸ‡¨ðŸ‡»",
    ioc: "CPV",
    languages: ["por"],
    name: "Cabo Verde",
    status: "assigned",
  },
  {
    alpha2: "CW",
    alpha3: "CUW",
    countryCallingCodes: ["599"],
    currencies: ["ANG"],
    emoji: "ðŸ‡¨ðŸ‡¼",
    ioc: "",
    languages: ["nld"],
    name: "Curacao",
    status: "assigned",
  },
  {
    alpha2: "CX",
    alpha3: "CXR",
    countryCallingCodes: ["61"],
    currencies: ["AUD"],
    emoji: "ðŸ‡¨ðŸ‡½",
    ioc: "",
    languages: ["eng"],
    name: "Christmas Island",
    status: "assigned",
  },
  {
    alpha2: "CY",
    alpha3: "CYP",
    countryCallingCodes: ["357"],
    currencies: ["EUR"],
    emoji: "ðŸ‡¨ðŸ‡¾",
    ioc: "CYP",
    languages: ["ell", "tur"],
    name: "Cyprus",
    status: "assigned",
  },
  {
    alpha2: "CZ",
    alpha3: "CZE",
    countryCallingCodes: ["420"],
    currencies: ["CZK"],
    emoji: "ðŸ‡¨ðŸ‡¿",
    ioc: "CZE",
    languages: ["ces"],
    name: "Czech Republic",
    status: "assigned",
  },
  {
    alpha2: "DD",
    alpha3: "DDR",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "German Democratic Republic",
    status: "deleted",
  },
  {
    alpha2: "DE",
    alpha3: "DEU",
    countryCallingCodes: ["49"],
    currencies: ["EUR"],
    emoji: "ðŸ‡©ðŸ‡ª",
    ioc: "GER",
    languages: ["deu"],
    name: "Germany",
    status: "assigned",
  },
  {
    alpha2: "DJ",
    alpha3: "DJI",
    countryCallingCodes: ["253"],
    currencies: ["DJF"],
    emoji: "ðŸ‡©ðŸ‡¯",
    ioc: "DJI",
    languages: ["ara", "fra"],
    name: "Djibouti",
    status: "assigned",
  },
  {
    alpha2: "DK",
    alpha3: "DNK",
    countryCallingCodes: ["45"],
    currencies: ["DKK"],
    emoji: "ðŸ‡©ðŸ‡°",
    ioc: "DEN",
    languages: ["dan"],
    name: "Denmark",
    status: "assigned",
  },
  {
    alpha2: "DM",
    alpha3: "DMA",
    countryCallingCodes: ["1 767"],
    currencies: ["XCD"],
    emoji: "ðŸ‡©ðŸ‡²",
    ioc: "DMA",
    languages: ["eng"],
    name: "Dominica",
    status: "assigned",
  },
  {
    alpha2: "DO",
    alpha3: "DOM",
    countryCallingCodes: ["1 809", "1 829", "1 849"],
    currencies: ["DOP"],
    emoji: "ðŸ‡©ðŸ‡´",
    ioc: "DOM",
    languages: ["spa"],
    name: "Dominican Republic",
    status: "assigned",
  },
  {
    alpha2: "DY",
    alpha3: "DHY",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "Dahomey",
    status: "deleted",
  },
  {
    alpha2: "DZ",
    alpha3: "DZA",
    countryCallingCodes: ["213"],
    currencies: ["DZD"],
    emoji: "ðŸ‡©ðŸ‡¿",
    ioc: "ALG",
    languages: ["ara"],
    name: "Algeria",
    status: "assigned",
  },
  {
    alpha2: "EC",
    alpha3: "ECU",
    countryCallingCodes: ["593"],
    currencies: ["USD"],
    emoji: "ðŸ‡ªðŸ‡¨",
    ioc: "ECU",
    languages: ["spa", "que"],
    name: "Ecuador",
    status: "assigned",
  },
  {
    alpha2: "EE",
    alpha3: "EST",
    countryCallingCodes: ["372"],
    currencies: ["EUR"],
    emoji: "ðŸ‡ªðŸ‡ª",
    ioc: "EST",
    languages: ["est"],
    name: "Estonia",
    status: "assigned",
  },
  {
    alpha2: "EG",
    alpha3: "EGY",
    countryCallingCodes: ["20"],
    currencies: ["EGP"],
    emoji: "ðŸ‡ªðŸ‡¬",
    ioc: "EGY",
    languages: ["ara"],
    name: "Egypt",
    status: "assigned",
  },
  {
    alpha2: "EH",
    alpha3: "ESH",
    countryCallingCodes: ["212"],
    currencies: ["MAD"],
    emoji: "ðŸ‡ªðŸ‡­",
    ioc: "",
    languages: [],
    name: "Western Sahara",
    status: "assigned",
  },
  {
    alpha2: "ER",
    alpha3: "ERI",
    countryCallingCodes: ["291"],
    currencies: ["ERN"],
    emoji: "ðŸ‡ªðŸ‡·",
    ioc: "ERI",
    languages: ["eng", "ara", "tir"],
    name: "Eritrea",
    status: "assigned",
  },
  {
    alpha2: "ES",
    alpha3: "ESP",
    countryCallingCodes: ["34"],
    currencies: ["EUR"],
    emoji: "ðŸ‡ªðŸ‡¸",
    ioc: "ESP",
    languages: ["spa"],
    name: "Spain",
    status: "assigned",
  },
  {
    alpha2: "ET",
    alpha3: "ETH",
    countryCallingCodes: ["251"],
    currencies: ["ETB"],
    emoji: "ðŸ‡ªðŸ‡¹",
    ioc: "ETH",
    languages: ["amh"],
    name: "Ethiopia",
    status: "assigned",
  },
  {
    alpha2: "EU",
    alpha3: "",
    countryCallingCodes: ["388"],
    currencies: ["EUR"],
    emoji: "ðŸ‡ªðŸ‡º",
    ioc: "",
    languages: [],
    name: "European Union",
    status: "reserved",
  },
  {
    alpha2: "FI",
    alpha3: "FIN",
    countryCallingCodes: ["358"],
    currencies: ["EUR"],
    emoji: "ðŸ‡«ðŸ‡®",
    ioc: "FIN",
    languages: ["fin", "swe"],
    name: "Finland",
    status: "assigned",
  },
  {
    alpha2: "FJ",
    alpha3: "FJI",
    countryCallingCodes: ["679"],
    currencies: ["FJD"],
    emoji: "ðŸ‡«ðŸ‡¯",
    ioc: "FIJ",
    languages: ["eng", "fij"],
    name: "Fiji",
    status: "assigned",
  },
  {
    alpha2: "FK",
    alpha3: "FLK",
    countryCallingCodes: ["500"],
    currencies: ["FKP"],
    emoji: "ðŸ‡«ðŸ‡°",
    ioc: "",
    languages: ["eng"],
    name: "Falkland Islands",
    status: "assigned",
  },
  {
    alpha2: "FM",
    alpha3: "FSM",
    countryCallingCodes: ["691"],
    currencies: ["USD"],
    emoji: "ðŸ‡«ðŸ‡²",
    ioc: "FSM",
    languages: ["eng"],
    name: "Micronesia, Federated States Of",
    status: "assigned",
  },
  {
    alpha2: "FO",
    alpha3: "FRO",
    countryCallingCodes: ["298"],
    currencies: ["DKK"],
    emoji: "ðŸ‡«ðŸ‡´",
    ioc: "FAI",
    languages: ["fao", "dan"],
    name: "Faroe Islands",
    status: "assigned",
  },
  {
    alpha2: "FQ",
    alpha3: "ATF",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "French Southern and Antarctic Territories",
    status: "deleted",
  },
  {
    alpha2: "FR",
    alpha3: "FRA",
    countryCallingCodes: ["33"],
    currencies: ["EUR"],
    emoji: "ðŸ‡«ðŸ‡·",
    ioc: "FRA",
    languages: ["fra"],
    name: "France",
    status: "assigned",
  },
  {
    alpha2: "GA",
    alpha3: "GAB",
    countryCallingCodes: ["241"],
    currencies: ["XAF"],
    emoji: "ðŸ‡¬ðŸ‡¦",
    ioc: "GAB",
    languages: ["fra"],
    name: "Gabon",
    status: "assigned",
  },
  {
    alpha2: "GB",
    alpha3: "GBR",
    countryCallingCodes: ["44"],
    currencies: ["GBP"],
    emoji: "ðŸ‡¬ðŸ‡§",
    ioc: "GBR",
    languages: ["eng", "cor", "gle", "gla", "cym"],
    name: "United Kingdom",
    status: "assigned",
  },
  {
    alpha2: "GD",
    alpha3: "GRD",
    countryCallingCodes: ["473"],
    currencies: ["XCD"],
    emoji: "ðŸ‡¬ðŸ‡©",
    ioc: "GRN",
    languages: ["eng"],
    name: "Grenada",
    status: "assigned",
  },
  {
    alpha2: "GE",
    alpha3: "GEO",
    countryCallingCodes: ["995"],
    currencies: ["GEL"],
    emoji: "ðŸ‡¬ðŸ‡ª",
    ioc: "GEO",
    languages: ["kat"],
    name: "Georgia",
    status: "assigned",
  },
  {
    alpha2: "GE",
    alpha3: "GEL",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "Gilbert and Ellice Islands",
    status: "deleted",
  },
  {
    alpha2: "GF",
    alpha3: "GUF",
    countryCallingCodes: ["594"],
    currencies: ["EUR"],
    emoji: "ðŸ‡¬ðŸ‡«",
    ioc: "",
    languages: ["fra"],
    name: "French Guiana",
    status: "assigned",
  },
  {
    alpha2: "GG",
    alpha3: "GGY",
    countryCallingCodes: ["44"],
    currencies: ["GBP"],
    emoji: "ðŸ‡¬ðŸ‡¬",
    ioc: "GCI",
    languages: ["fra"],
    name: "Guernsey",
    status: "assigned",
  },
  {
    alpha2: "GH",
    alpha3: "GHA",
    countryCallingCodes: ["233"],
    currencies: ["GHS"],
    emoji: "ðŸ‡¬ðŸ‡­",
    ioc: "GHA",
    languages: ["eng"],
    name: "Ghana",
    status: "assigned",
  },
  {
    alpha2: "GI",
    alpha3: "GIB",
    countryCallingCodes: ["350"],
    currencies: ["GIP"],
    emoji: "ðŸ‡¬ðŸ‡®",
    ioc: "",
    languages: ["eng"],
    name: "Gibraltar",
    status: "assigned",
  },
  {
    alpha2: "GL",
    alpha3: "GRL",
    countryCallingCodes: ["299"],
    currencies: ["DKK"],
    emoji: "ðŸ‡¬ðŸ‡±",
    ioc: "",
    languages: ["kal"],
    name: "Greenland",
    status: "assigned",
  },
  {
    alpha2: "GM",
    alpha3: "GMB",
    countryCallingCodes: ["220"],
    currencies: ["GMD"],
    emoji: "ðŸ‡¬ðŸ‡²",
    ioc: "GAM",
    languages: ["eng"],
    name: "Gambia",
    status: "assigned",
  },
  {
    alpha2: "GN",
    alpha3: "GIN",
    countryCallingCodes: ["224"],
    currencies: ["GNF"],
    emoji: "ðŸ‡¬ðŸ‡³",
    ioc: "GUI",
    languages: ["fra"],
    name: "Guinea",
    status: "assigned",
  },
  {
    alpha2: "GP",
    alpha3: "GLP",
    countryCallingCodes: ["590"],
    currencies: ["EUR"],
    emoji: "ðŸ‡¬ðŸ‡µ",
    ioc: "",
    languages: ["fra"],
    name: "Guadeloupe",
    status: "assigned",
  },
  {
    alpha2: "GQ",
    alpha3: "GNQ",
    countryCallingCodes: ["240"],
    currencies: ["XAF"],
    emoji: "ðŸ‡¬ðŸ‡¶",
    ioc: "GEQ",
    languages: ["spa", "fra", "por"],
    name: "Equatorial Guinea",
    status: "assigned",
  },
  {
    alpha2: "GR",
    alpha3: "GRC",
    countryCallingCodes: ["30"],
    currencies: ["EUR"],
    emoji: "ðŸ‡¬ðŸ‡·",
    ioc: "GRE",
    languages: ["ell"],
    name: "Greece",
    status: "assigned",
  },
  {
    alpha2: "GS",
    alpha3: "SGS",
    countryCallingCodes: [],
    currencies: ["GBP"],
    emoji: "ðŸ‡¬ðŸ‡¸",
    ioc: "",
    languages: ["eng"],
    name: "South Georgia And The South Sandwich Islands",
    status: "assigned",
  },
  {
    alpha2: "GT",
    alpha3: "GTM",
    countryCallingCodes: ["502"],
    currencies: ["GTQ"],
    emoji: "ðŸ‡¬ðŸ‡¹",
    ioc: "GUA",
    languages: ["spa"],
    name: "Guatemala",
    status: "assigned",
  },
  {
    alpha2: "GU",
    alpha3: "GUM",
    countryCallingCodes: ["1 671"],
    currencies: ["USD"],
    emoji: "ðŸ‡¬ðŸ‡º",
    ioc: "GUM",
    languages: ["eng"],
    name: "Guam",
    status: "assigned",
  },
  {
    alpha2: "GW",
    alpha3: "GNB",
    countryCallingCodes: ["245"],
    currencies: ["XOF"],
    emoji: "ðŸ‡¬ðŸ‡¼",
    ioc: "GBS",
    languages: ["por"],
    name: "Guinea-bissau",
    status: "assigned",
  },
  {
    alpha2: "GY",
    alpha3: "GUY",
    countryCallingCodes: ["592"],
    currencies: ["GYD"],
    emoji: "ðŸ‡¬ðŸ‡¾",
    ioc: "GUY",
    languages: ["eng"],
    name: "Guyana",
    status: "assigned",
  },
  {
    alpha2: "HK",
    alpha3: "HKG",
    countryCallingCodes: ["852"],
    currencies: ["HKD"],
    emoji: "ðŸ‡­ðŸ‡°",
    ioc: "HKG",
    languages: ["zho", "eng"],
    name: "Hong Kong",
    status: "assigned",
  },
  {
    alpha2: "HM",
    alpha3: "HMD",
    countryCallingCodes: [],
    currencies: ["AUD"],
    emoji: "ðŸ‡­ðŸ‡²",
    ioc: "",
    languages: [],
    name: "Heard Island And McDonald Islands",
    status: "assigned",
  },
  {
    alpha2: "HN",
    alpha3: "HND",
    countryCallingCodes: ["504"],
    currencies: ["HNL"],
    emoji: "ðŸ‡­ðŸ‡³",
    ioc: "HON",
    languages: ["spa"],
    name: "Honduras",
    status: "assigned",
  },
  {
    alpha2: "HR",
    alpha3: "HRV",
    countryCallingCodes: ["385"],
    currencies: ["HRK"],
    emoji: "ðŸ‡­ðŸ‡·",
    ioc: "CRO",
    languages: ["hrv"],
    name: "Croatia",
    status: "assigned",
  },
  {
    alpha2: "HT",
    alpha3: "HTI",
    countryCallingCodes: ["509"],
    currencies: ["HTG", "USD"],
    emoji: "ðŸ‡­ðŸ‡¹",
    ioc: "HAI",
    languages: ["fra", "hat"],
    name: "Haiti",
    status: "assigned",
  },
  {
    alpha2: "HU",
    alpha3: "HUN",
    countryCallingCodes: ["36"],
    currencies: ["HUF"],
    emoji: "ðŸ‡­ðŸ‡º",
    ioc: "HUN",
    languages: ["hun"],
    name: "Hungary",
    status: "assigned",
  },
  {
    alpha2: "HV",
    alpha3: "HVO",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "Upper Volta",
    status: "deleted",
  },
  {
    alpha2: "ID",
    alpha3: "IDN",
    countryCallingCodes: ["62"],
    currencies: ["IDR"],
    emoji: "ðŸ‡®ðŸ‡©",
    ioc: "INA",
    languages: ["ind"],
    name: "Indonesia",
    status: "assigned",
  },
  {
    alpha2: "IE",
    alpha3: "IRL",
    countryCallingCodes: ["353"],
    currencies: ["EUR"],
    emoji: "ðŸ‡®ðŸ‡ª",
    ioc: "IRL",
    languages: ["eng", "gle"],
    name: "Ireland",
    status: "assigned",
  },
  {
    alpha2: "IL",
    alpha3: "ISR",
    countryCallingCodes: ["972"],
    currencies: ["ILS"],
    emoji: "ðŸ‡®ðŸ‡±",
    ioc: "ISR",
    languages: ["heb", "ara", "eng"],
    name: "Israel",
    status: "assigned",
  },
  {
    alpha2: "IM",
    alpha3: "IMN",
    countryCallingCodes: ["44"],
    currencies: ["GBP"],
    emoji: "ðŸ‡®ðŸ‡²",
    ioc: "",
    languages: ["eng", "glv"],
    name: "Isle Of Man",
    status: "assigned",
  },
  {
    alpha2: "IN",
    alpha3: "IND",
    countryCallingCodes: ["91"],
    currencies: ["INR"],
    emoji: "ðŸ‡®ðŸ‡³",
    ioc: "IND",
    languages: ["eng", "hin"],
    name: "India",
    status: "assigned",
  },
  {
    alpha2: "IO",
    alpha3: "IOT",
    countryCallingCodes: ["246"],
    currencies: ["USD"],
    emoji: "ðŸ‡®ðŸ‡´",
    ioc: "",
    languages: ["eng"],
    name: "British Indian Ocean Territory",
    status: "assigned",
  },
  {
    alpha2: "IQ",
    alpha3: "IRQ",
    countryCallingCodes: ["964"],
    currencies: ["IQD"],
    emoji: "ðŸ‡®ðŸ‡¶",
    ioc: "IRQ",
    languages: ["ara", "kur"],
    name: "Iraq",
    status: "assigned",
  },
  {
    alpha2: "IR",
    alpha3: "IRN",
    countryCallingCodes: ["98"],
    currencies: ["IRR"],
    emoji: "ðŸ‡®ðŸ‡·",
    ioc: "IRI",
    languages: ["fas"],
    name: "Iran, Islamic Republic Of",
    status: "assigned",
  },
  {
    alpha2: "IS",
    alpha3: "ISL",
    countryCallingCodes: ["354"],
    currencies: ["ISK"],
    emoji: "ðŸ‡®ðŸ‡¸",
    ioc: "ISL",
    languages: ["isl"],
    name: "Iceland",
    status: "assigned",
  },
  {
    alpha2: "IT",
    alpha3: "ITA",
    countryCallingCodes: ["39"],
    currencies: ["EUR"],
    emoji: "ðŸ‡®ðŸ‡¹",
    ioc: "ITA",
    languages: ["ita"],
    name: "Italy",
    status: "assigned",
  },
  {
    alpha2: "JE",
    alpha3: "JEY",
    countryCallingCodes: ["44"],
    currencies: ["GBP"],
    emoji: "ðŸ‡¯ðŸ‡ª",
    ioc: "JCI",
    languages: ["eng", "fra"],
    name: "Jersey",
    status: "assigned",
  },
  {
    alpha2: "JM",
    alpha3: "JAM",
    countryCallingCodes: ["1 876"],
    currencies: ["JMD"],
    emoji: "ðŸ‡¯ðŸ‡²",
    ioc: "JAM",
    languages: ["eng"],
    name: "Jamaica",
    status: "assigned",
  },
  {
    alpha2: "JO",
    alpha3: "JOR",
    countryCallingCodes: ["962"],
    currencies: ["JOD"],
    emoji: "ðŸ‡¯ðŸ‡´",
    ioc: "JOR",
    languages: ["ara"],
    name: "Jordan",
    status: "assigned",
  },
  {
    alpha2: "JP",
    alpha3: "JPN",
    countryCallingCodes: ["81"],
    currencies: ["JPY"],
    emoji: "ðŸ‡¯ðŸ‡µ",
    ioc: "JPN",
    languages: ["jpn"],
    name: "Japan",
    status: "assigned",
  },
  {
    alpha2: "JT",
    alpha3: "JTN",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "Johnston Island",
    status: "deleted",
  },
  {
    alpha2: "KE",
    alpha3: "KEN",
    countryCallingCodes: ["254"],
    currencies: ["KES"],
    emoji: "ðŸ‡°ðŸ‡ª",
    ioc: "KEN",
    languages: ["eng", "swa"],
    name: "Kenya",
    status: "assigned",
  },
  {
    alpha2: "KG",
    alpha3: "KGZ",
    countryCallingCodes: ["996"],
    currencies: ["KGS"],
    emoji: "ðŸ‡°ðŸ‡¬",
    ioc: "KGZ",
    languages: ["rus"],
    name: "Kyrgyzstan",
    status: "assigned",
  },
  {
    alpha2: "KH",
    alpha3: "KHM",
    countryCallingCodes: ["855"],
    currencies: ["KHR"],
    emoji: "ðŸ‡°ðŸ‡­",
    ioc: "CAM",
    languages: ["khm"],
    name: "Cambodia",
    status: "assigned",
  },
  {
    alpha2: "KI",
    alpha3: "KIR",
    countryCallingCodes: ["686"],
    currencies: ["AUD"],
    emoji: "ðŸ‡°ðŸ‡®",
    ioc: "KIR",
    languages: ["eng"],
    name: "Kiribati",
    status: "assigned",
  },
  {
    alpha2: "KM",
    alpha3: "COM",
    countryCallingCodes: ["269"],
    currencies: ["KMF"],
    emoji: "ðŸ‡°ðŸ‡²",
    ioc: "COM",
    languages: ["ara", "fra"],
    name: "Comoros",
    status: "assigned",
  },
  {
    alpha2: "KN",
    alpha3: "KNA",
    countryCallingCodes: ["1 869"],
    currencies: ["XCD"],
    emoji: "ðŸ‡°ðŸ‡³",
    ioc: "SKN",
    languages: ["eng"],
    name: "Saint Kitts And Nevis",
    status: "assigned",
  },
  {
    alpha2: "KP",
    alpha3: "PRK",
    countryCallingCodes: ["850"],
    currencies: ["KPW"],
    emoji: "ðŸ‡°ðŸ‡µ",
    ioc: "PRK",
    languages: ["kor"],
    name: "Korea, Democratic People's Republic Of",
    status: "assigned",
  },
  {
    alpha2: "KR",
    alpha3: "KOR",
    countryCallingCodes: ["82"],
    currencies: ["KRW"],
    emoji: "ðŸ‡°ðŸ‡·",
    ioc: "KOR",
    languages: ["kor"],
    name: "Korea, Republic Of",
    status: "assigned",
  },
  {
    alpha2: "KW",
    alpha3: "KWT",
    countryCallingCodes: ["965"],
    currencies: ["KWD"],
    emoji: "ðŸ‡°ðŸ‡¼",
    ioc: "KUW",
    languages: ["ara"],
    name: "Kuwait",
    status: "assigned",
  },
  {
    alpha2: "KY",
    alpha3: "CYM",
    countryCallingCodes: ["1 345"],
    currencies: ["KYD"],
    emoji: "ðŸ‡°ðŸ‡¾",
    ioc: "CAY",
    languages: ["eng"],
    name: "Cayman Islands",
    status: "assigned",
  },
  {
    alpha2: "KZ",
    alpha3: "KAZ",
    countryCallingCodes: ["7", "7 6", "7 7"],
    currencies: ["KZT"],
    emoji: "ðŸ‡°ðŸ‡¿",
    ioc: "KAZ",
    languages: ["kaz", "rus"],
    name: "Kazakhstan",
    status: "assigned",
  },
  {
    alpha2: "LA",
    alpha3: "LAO",
    countryCallingCodes: ["856"],
    currencies: ["LAK"],
    emoji: "ðŸ‡±ðŸ‡¦",
    ioc: "LAO",
    languages: ["lao"],
    name: "Lao People's Democratic Republic",
    status: "assigned",
  },
  {
    alpha2: "LB",
    alpha3: "LBN",
    countryCallingCodes: ["961"],
    currencies: ["LBP"],
    emoji: "ðŸ‡±ðŸ‡§",
    ioc: "LIB",
    languages: ["ara", "hye"],
    name: "Lebanon",
    status: "assigned",
  },
  {
    alpha2: "LC",
    alpha3: "LCA",
    countryCallingCodes: ["1 758"],
    currencies: ["XCD"],
    emoji: "ðŸ‡±ðŸ‡¨",
    ioc: "LCA",
    languages: ["eng"],
    name: "Saint Lucia",
    status: "assigned",
  },
  {
    alpha2: "LI",
    alpha3: "LIE",
    countryCallingCodes: ["423"],
    currencies: ["CHF"],
    emoji: "ðŸ‡±ðŸ‡®",
    ioc: "LIE",
    languages: ["deu"],
    name: "Liechtenstein",
    status: "assigned",
  },
  {
    alpha2: "LK",
    alpha3: "LKA",
    countryCallingCodes: ["94"],
    currencies: ["LKR"],
    emoji: "ðŸ‡±ðŸ‡°",
    ioc: "SRI",
    languages: ["sin", "tam"],
    name: "Sri Lanka",
    status: "assigned",
  },
  {
    alpha2: "LR",
    alpha3: "LBR",
    countryCallingCodes: ["231"],
    currencies: ["LRD"],
    emoji: "ðŸ‡±ðŸ‡·",
    ioc: "LBR",
    languages: ["eng"],
    name: "Liberia",
    status: "assigned",
  },
  {
    alpha2: "LS",
    alpha3: "LSO",
    countryCallingCodes: ["266"],
    currencies: ["LSL", "ZAR"],
    emoji: "ðŸ‡±ðŸ‡¸",
    ioc: "LES",
    languages: ["eng", "sot"],
    name: "Lesotho",
    status: "assigned",
  },
  {
    alpha2: "LT",
    alpha3: "LTU",
    countryCallingCodes: ["370"],
    currencies: ["EUR"],
    emoji: "ðŸ‡±ðŸ‡¹",
    ioc: "LTU",
    languages: ["lit"],
    name: "Lithuania",
    status: "assigned",
  },
  {
    alpha2: "LU",
    alpha3: "LUX",
    countryCallingCodes: ["352"],
    currencies: ["EUR"],
    emoji: "ðŸ‡±ðŸ‡º",
    ioc: "LUX",
    languages: ["fra", "deu", "ltz"],
    name: "Luxembourg",
    status: "assigned",
  },
  {
    alpha2: "LV",
    alpha3: "LVA",
    countryCallingCodes: ["371"],
    currencies: ["EUR"],
    emoji: "ðŸ‡±ðŸ‡»",
    ioc: "LAT",
    languages: ["lav"],
    name: "Latvia",
    status: "assigned",
  },
  {
    alpha2: "LY",
    alpha3: "LBY",
    countryCallingCodes: ["218"],
    currencies: ["LYD"],
    emoji: "ðŸ‡±ðŸ‡¾",
    ioc: "LBA",
    languages: ["ara"],
    name: "Libya",
    status: "assigned",
  },
  {
    alpha2: "MA",
    alpha3: "MAR",
    countryCallingCodes: ["212"],
    currencies: ["MAD"],
    emoji: "ðŸ‡²ðŸ‡¦",
    ioc: "MAR",
    languages: ["ara"],
    name: "Morocco",
    status: "assigned",
  },
  {
    alpha2: "MC",
    alpha3: "MCO",
    countryCallingCodes: ["377"],
    currencies: ["EUR"],
    emoji: "ðŸ‡²ðŸ‡¨",
    ioc: "MON",
    languages: ["fra"],
    name: "Monaco",
    status: "assigned",
  },
  {
    alpha2: "MD",
    alpha3: "MDA",
    countryCallingCodes: ["373"],
    currencies: ["MDL"],
    emoji: "ðŸ‡²ðŸ‡©",
    ioc: "MDA",
    languages: ["ron"],
    name: "Moldova",
    status: "assigned",
  },
  {
    alpha2: "ME",
    alpha3: "MNE",
    countryCallingCodes: ["382"],
    currencies: ["EUR"],
    emoji: "ðŸ‡²ðŸ‡ª",
    ioc: "MNE",
    languages: ["mot"],
    name: "Montenegro",
    status: "assigned",
  },
  {
    alpha2: "MF",
    alpha3: "MAF",
    countryCallingCodes: ["590"],
    currencies: ["EUR"],
    emoji: "ðŸ‡²ðŸ‡«",
    ioc: "",
    languages: ["fra"],
    name: "Saint Martin",
    status: "assigned",
  },
  {
    alpha2: "MG",
    alpha3: "MDG",
    countryCallingCodes: ["261"],
    currencies: ["MGA"],
    emoji: "ðŸ‡²ðŸ‡¬",
    ioc: "MAD",
    languages: ["fra", "mlg"],
    name: "Madagascar",
    status: "assigned",
  },
  {
    alpha2: "MH",
    alpha3: "MHL",
    countryCallingCodes: ["692"],
    currencies: ["USD"],
    emoji: "ðŸ‡²ðŸ‡­",
    ioc: "MHL",
    languages: ["eng", "mah"],
    name: "Marshall Islands",
    status: "assigned",
  },
  {
    alpha2: "MI",
    alpha3: "MID",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "Midway Islands",
    status: "deleted",
  },
  {
    alpha2: "MK",
    alpha3: "MKD",
    countryCallingCodes: ["389"],
    currencies: ["MKD"],
    emoji: "ðŸ‡²ðŸ‡°",
    ioc: "MKD",
    languages: ["mkd"],
    name: "Macedonia, The Former Yugoslav Republic Of",
    status: "assigned",
  },
  {
    alpha2: "ML",
    alpha3: "MLI",
    countryCallingCodes: ["223"],
    currencies: ["XOF"],
    emoji: "ðŸ‡²ðŸ‡±",
    ioc: "MLI",
    languages: ["fra"],
    name: "Mali",
    status: "assigned",
  },
  {
    alpha2: "MM",
    alpha3: "MMR",
    countryCallingCodes: ["95"],
    currencies: ["MMK"],
    emoji: "ðŸ‡²ðŸ‡²",
    ioc: "MYA",
    languages: ["mya"],
    name: "Myanmar",
    status: "assigned",
  },
  {
    alpha2: "MN",
    alpha3: "MNG",
    countryCallingCodes: ["976"],
    currencies: ["MNT"],
    emoji: "ðŸ‡²ðŸ‡³",
    ioc: "MGL",
    languages: ["mon"],
    name: "Mongolia",
    status: "assigned",
  },
  {
    alpha2: "MO",
    alpha3: "MAC",
    countryCallingCodes: ["853"],
    currencies: ["MOP"],
    emoji: "ðŸ‡²ðŸ‡´",
    ioc: "MAC",
    languages: ["zho", "por"],
    name: "Macao",
    status: "assigned",
  },
  {
    alpha2: "MP",
    alpha3: "MNP",
    countryCallingCodes: ["1 670"],
    currencies: ["USD"],
    emoji: "ðŸ‡²ðŸ‡µ",
    ioc: "",
    languages: ["eng"],
    name: "Northern Mariana Islands",
    status: "assigned",
  },
  {
    alpha2: "MQ",
    alpha3: "MTQ",
    countryCallingCodes: ["596"],
    currencies: ["EUR"],
    emoji: "ðŸ‡²ðŸ‡¶",
    ioc: "",
    languages: [],
    name: "Martinique",
    status: "assigned",
  },
  {
    alpha2: "MR",
    alpha3: "MRT",
    countryCallingCodes: ["222"],
    currencies: ["MRO"],
    emoji: "ðŸ‡²ðŸ‡·",
    ioc: "MTN",
    languages: ["ara", "fra"],
    name: "Mauritania",
    status: "assigned",
  },
  {
    alpha2: "MS",
    alpha3: "MSR",
    countryCallingCodes: ["1 664"],
    currencies: ["XCD"],
    emoji: "ðŸ‡²ðŸ‡¸",
    ioc: "",
    languages: [],
    name: "Montserrat",
    status: "assigned",
  },
  {
    alpha2: "MT",
    alpha3: "MLT",
    countryCallingCodes: ["356"],
    currencies: ["EUR"],
    emoji: "ðŸ‡²ðŸ‡¹",
    ioc: "MLT",
    languages: ["mlt", "eng"],
    name: "Malta",
    status: "assigned",
  },
  {
    alpha2: "MU",
    alpha3: "MUS",
    countryCallingCodes: ["230"],
    currencies: ["MUR"],
    emoji: "ðŸ‡²ðŸ‡º",
    ioc: "MRI",
    languages: ["eng", "fra"],
    name: "Mauritius",
    status: "assigned",
  },
  {
    alpha2: "MV",
    alpha3: "MDV",
    countryCallingCodes: ["960"],
    currencies: ["MVR"],
    emoji: "ðŸ‡²ðŸ‡»",
    ioc: "MDV",
    languages: ["div"],
    name: "Maldives",
    status: "assigned",
  },
  {
    alpha2: "MW",
    alpha3: "MWI",
    countryCallingCodes: ["265"],
    currencies: ["MWK"],
    emoji: "ðŸ‡²ðŸ‡¼",
    ioc: "MAW",
    languages: ["eng", "nya"],
    name: "Malawi",
    status: "assigned",
  },
  {
    alpha2: "MX",
    alpha3: "MEX",
    countryCallingCodes: ["52"],
    currencies: ["MXN", "MXV"],
    emoji: "ðŸ‡²ðŸ‡½",
    ioc: "MEX",
    languages: ["spa"],
    name: "Mexico",
    status: "assigned",
  },
  {
    alpha2: "MY",
    alpha3: "MYS",
    countryCallingCodes: ["60"],
    currencies: ["MYR"],
    emoji: "ðŸ‡²ðŸ‡¾",
    ioc: "MAS",
    languages: ["msa", "eng"],
    name: "Malaysia",
    status: "assigned",
  },
  {
    alpha2: "MZ",
    alpha3: "MOZ",
    countryCallingCodes: ["258"],
    currencies: ["MZN"],
    emoji: "ðŸ‡²ðŸ‡¿",
    ioc: "MOZ",
    languages: ["por"],
    name: "Mozambique",
    status: "assigned",
  },
  {
    alpha2: "NA",
    alpha3: "NAM",
    countryCallingCodes: ["264"],
    currencies: ["NAD", "ZAR"],
    emoji: "ðŸ‡³ðŸ‡¦",
    ioc: "NAM",
    languages: ["eng"],
    name: "Namibia",
    status: "assigned",
  },
  {
    alpha2: "NC",
    alpha3: "NCL",
    countryCallingCodes: ["687"],
    currencies: ["XPF"],
    emoji: "ðŸ‡³ðŸ‡¨",
    ioc: "",
    languages: ["fra"],
    name: "New Caledonia",
    status: "assigned",
  },
  {
    alpha2: "NE",
    alpha3: "NER",
    countryCallingCodes: ["227"],
    currencies: ["XOF"],
    emoji: "ðŸ‡³ðŸ‡ª",
    ioc: "NIG",
    languages: ["fra"],
    name: "Niger",
    status: "assigned",
  },
  {
    alpha2: "NF",
    alpha3: "NFK",
    countryCallingCodes: ["672"],
    currencies: ["AUD"],
    emoji: "ðŸ‡³ðŸ‡«",
    ioc: "",
    languages: ["eng"],
    name: "Norfolk Island",
    status: "assigned",
  },
  {
    alpha2: "NG",
    alpha3: "NGA",
    countryCallingCodes: ["234"],
    currencies: ["NGN"],
    emoji: "ðŸ‡³ðŸ‡¬",
    ioc: "NGR",
    languages: ["eng"],
    name: "Nigeria",
    status: "assigned",
  },
  {
    alpha2: "NH",
    alpha3: "NHB",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "New Hebrides",
    status: "deleted",
  },
  {
    alpha2: "NI",
    alpha3: "NIC",
    countryCallingCodes: ["505"],
    currencies: ["NIO"],
    emoji: "ðŸ‡³ðŸ‡®",
    ioc: "NCA",
    languages: ["spa"],
    name: "Nicaragua",
    status: "assigned",
  },
  {
    alpha2: "NL",
    alpha3: "NLD",
    countryCallingCodes: ["31"],
    currencies: ["EUR"],
    emoji: "ðŸ‡³ðŸ‡±",
    ioc: "NED",
    languages: ["nld"],
    name: "Netherlands",
    status: "assigned",
  },
  {
    alpha2: "NO",
    alpha3: "NOR",
    countryCallingCodes: ["47"],
    currencies: ["NOK"],
    emoji: "ðŸ‡³ðŸ‡´",
    ioc: "NOR",
    languages: ["nor"],
    name: "Norway",
    status: "assigned",
  },
  {
    alpha2: "NP",
    alpha3: "NPL",
    countryCallingCodes: ["977"],
    currencies: ["NPR"],
    emoji: "ðŸ‡³ðŸ‡µ",
    ioc: "NEP",
    languages: ["nep"],
    name: "Nepal",
    status: "assigned",
  },
  {
    alpha2: "NQ",
    alpha3: "ATN",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "Dronning Maud Land",
    status: "deleted",
  },
  {
    alpha2: "NR",
    alpha3: "NRU",
    countryCallingCodes: ["674"],
    currencies: ["AUD"],
    emoji: "ðŸ‡³ðŸ‡·",
    ioc: "NRU",
    languages: ["eng", "nau"],
    name: "Nauru",
    status: "assigned",
  },
  {
    alpha2: "NT",
    alpha3: "NTZ",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "Neutral Zone",
    status: "deleted",
  },
  {
    alpha2: "NU",
    alpha3: "NIU",
    countryCallingCodes: ["683"],
    currencies: ["NZD"],
    emoji: "ðŸ‡³ðŸ‡º",
    ioc: "",
    languages: ["eng"],
    name: "Niue",
    status: "assigned",
  },
  {
    alpha2: "NZ",
    alpha3: "NZL",
    countryCallingCodes: ["64"],
    currencies: ["NZD"],
    emoji: "ðŸ‡³ðŸ‡¿",
    ioc: "NZL",
    languages: ["eng"],
    name: "New Zealand",
    status: "assigned",
  },
  {
    alpha2: "OM",
    alpha3: "OMN",
    countryCallingCodes: ["968"],
    currencies: ["OMR"],
    emoji: "ðŸ‡´ðŸ‡²",
    ioc: "OMA",
    languages: ["ara"],
    name: "Oman",
    status: "assigned",
  },
  {
    alpha2: "PA",
    alpha3: "PAN",
    countryCallingCodes: ["507"],
    currencies: ["PAB", "USD"],
    emoji: "ðŸ‡µðŸ‡¦",
    ioc: "PAN",
    languages: ["spa"],
    name: "Panama",
    status: "assigned",
  },
  {
    alpha2: "PC",
    alpha3: "PCI",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "Pacific Islands, Trust Territory of the",
    status: "deleted",
  },
  {
    alpha2: "PE",
    alpha3: "PER",
    countryCallingCodes: ["51"],
    currencies: ["PEN"],
    emoji: "ðŸ‡µðŸ‡ª",
    ioc: "PER",
    languages: ["spa", "aym", "que"],
    name: "Peru",
    status: "assigned",
  },
  {
    alpha2: "PF",
    alpha3: "PYF",
    countryCallingCodes: ["689"],
    currencies: ["XPF"],
    emoji: "ðŸ‡µðŸ‡«",
    ioc: "",
    languages: ["fra"],
    name: "French Polynesia",
    status: "assigned",
  },
  {
    alpha2: "PG",
    alpha3: "PNG",
    countryCallingCodes: ["675"],
    currencies: ["PGK"],
    emoji: "ðŸ‡µðŸ‡¬",
    ioc: "PNG",
    languages: ["eng"],
    name: "Papua New Guinea",
    status: "assigned",
  },
  {
    alpha2: "PH",
    alpha3: "PHL",
    countryCallingCodes: ["63"],
    currencies: ["PHP"],
    emoji: "ðŸ‡µðŸ‡­",
    ioc: "PHI",
    languages: ["eng"],
    name: "Philippines",
    status: "assigned",
  },
  {
    alpha2: "PK",
    alpha3: "PAK",
    countryCallingCodes: ["92"],
    currencies: ["PKR"],
    emoji: "ðŸ‡µðŸ‡°",
    ioc: "PAK",
    languages: ["urd", "eng"],
    name: "Pakistan",
    status: "assigned",
  },
  {
    alpha2: "PL",
    alpha3: "POL",
    countryCallingCodes: ["48"],
    currencies: ["PLN"],
    emoji: "ðŸ‡µðŸ‡±",
    ioc: "POL",
    languages: ["pol"],
    name: "Poland",
    status: "assigned",
  },
  {
    alpha2: "PM",
    alpha3: "SPM",
    countryCallingCodes: ["508"],
    currencies: ["EUR"],
    emoji: "ðŸ‡µðŸ‡²",
    ioc: "",
    languages: ["eng"],
    name: "Saint Pierre And Miquelon",
    status: "assigned",
  },
  {
    alpha2: "PN",
    alpha3: "PCN",
    countryCallingCodes: ["872"],
    currencies: ["NZD"],
    emoji: "ðŸ‡µðŸ‡³",
    ioc: "",
    languages: ["eng"],
    name: "Pitcairn",
    status: "assigned",
  },
  {
    alpha2: "PR",
    alpha3: "PRI",
    countryCallingCodes: ["1 787", "1 939"],
    currencies: ["USD"],
    emoji: "ðŸ‡µðŸ‡·",
    ioc: "PUR",
    languages: ["spa", "eng"],
    name: "Puerto Rico",
    status: "assigned",
  },
  {
    alpha2: "PS",
    alpha3: "PSE",
    countryCallingCodes: ["970"],
    currencies: ["JOD", "EGP", "ILS"],
    emoji: "ðŸ‡µðŸ‡¸",
    ioc: "PLE",
    languages: ["ara"],
    name: "Palestinian Territory, Occupied",
    status: "assigned",
  },
  {
    alpha2: "PT",
    alpha3: "PRT",
    countryCallingCodes: ["351"],
    currencies: ["EUR"],
    emoji: "ðŸ‡µðŸ‡¹",
    ioc: "POR",
    languages: ["por"],
    name: "Portugal",
    status: "assigned",
  },
  {
    alpha2: "PU",
    alpha3: "PUS",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "U.S. Miscellaneous Pacific Islands",
    status: "deleted",
  },
  {
    alpha2: "PW",
    alpha3: "PLW",
    countryCallingCodes: ["680"],
    currencies: ["USD"],
    emoji: "ðŸ‡µðŸ‡¼",
    ioc: "PLW",
    languages: ["eng"],
    name: "Palau",
    status: "assigned",
  },
  {
    alpha2: "PY",
    alpha3: "PRY",
    countryCallingCodes: ["595"],
    currencies: ["PYG"],
    emoji: "ðŸ‡µðŸ‡¾",
    ioc: "PAR",
    languages: ["spa"],
    name: "Paraguay",
    status: "assigned",
  },
  {
    alpha2: "PZ",
    alpha3: "PCZ",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "Panama Canal Zone",
    status: "deleted",
  },
  {
    alpha2: "QA",
    alpha3: "QAT",
    countryCallingCodes: ["974"],
    currencies: ["QAR"],
    emoji: "ðŸ‡¶ðŸ‡¦",
    ioc: "QAT",
    languages: ["ara"],
    name: "Qatar",
    status: "assigned",
  },
  {
    alpha2: "RE",
    alpha3: "REU",
    countryCallingCodes: ["262"],
    currencies: ["EUR"],
    emoji: "ðŸ‡·ðŸ‡ª",
    ioc: "",
    languages: ["fra"],
    name: "Reunion",
    status: "assigned",
  },
  {
    alpha2: "RH",
    alpha3: "RHO",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "Southern Rhodesia",
    status: "deleted",
  },
  {
    alpha2: "RO",
    alpha3: "ROU",
    countryCallingCodes: ["40"],
    currencies: ["RON"],
    emoji: "ðŸ‡·ðŸ‡´",
    ioc: "ROU",
    languages: ["ron"],
    name: "Romania",
    status: "assigned",
  },
  {
    alpha2: "RS",
    alpha3: "SRB",
    countryCallingCodes: ["381"],
    currencies: ["RSD"],
    emoji: "ðŸ‡·ðŸ‡¸",
    ioc: "SRB",
    languages: ["srp"],
    name: "Serbia",
    status: "assigned",
  },
  {
    alpha2: "RU",
    alpha3: "RUS",
    countryCallingCodes: ["7", "7 3", "7 4", "7 8"],
    currencies: ["RUB"],
    emoji: "ðŸ‡·ðŸ‡º",
    ioc: "RUS",
    languages: ["rus"],
    name: "Russian Federation",
    status: "assigned",
  },
  {
    alpha2: "RW",
    alpha3: "RWA",
    countryCallingCodes: ["250"],
    currencies: ["RWF"],
    emoji: "ðŸ‡·ðŸ‡¼",
    ioc: "RWA",
    languages: ["eng", "fra", "kin"],
    name: "Rwanda",
    status: "assigned",
  },
  {
    alpha2: "SA",
    alpha3: "SAU",
    countryCallingCodes: ["966"],
    currencies: ["SAR"],
    emoji: "ðŸ‡¸ðŸ‡¦",
    ioc: "KSA",
    languages: ["ara"],
    name: "Saudi Arabia",
    status: "assigned",
  },
  {
    alpha2: "SB",
    alpha3: "SLB",
    countryCallingCodes: ["677"],
    currencies: ["SBD"],
    emoji: "ðŸ‡¸ðŸ‡§",
    ioc: "SOL",
    languages: ["eng"],
    name: "Solomon Islands",
    status: "assigned",
  },
  {
    alpha2: "SC",
    alpha3: "SYC",
    countryCallingCodes: ["248"],
    currencies: ["SCR"],
    emoji: "ðŸ‡¸ðŸ‡¨",
    ioc: "SEY",
    languages: ["eng", "fra"],
    name: "Seychelles",
    status: "assigned",
  },
  {
    alpha2: "SD",
    alpha3: "SDN",
    countryCallingCodes: ["249"],
    currencies: ["SDG"],
    emoji: "ðŸ‡¸ðŸ‡©",
    ioc: "SUD",
    languages: ["ara", "eng"],
    name: "Sudan",
    status: "assigned",
  },
  {
    alpha2: "SE",
    alpha3: "SWE",
    countryCallingCodes: ["46"],
    currencies: ["SEK"],
    emoji: "ðŸ‡¸ðŸ‡ª",
    ioc: "SWE",
    languages: ["swe"],
    name: "Sweden",
    status: "assigned",
  },
  {
    alpha2: "SG",
    alpha3: "SGP",
    countryCallingCodes: ["65"],
    currencies: ["SGD"],
    emoji: "ðŸ‡¸ðŸ‡¬",
    ioc: "SIN",
    languages: ["eng", "zho", "msa", "tam"],
    name: "Singapore",
    status: "assigned",
  },
  {
    alpha2: "SH",
    alpha3: "SHN",
    countryCallingCodes: ["290"],
    currencies: ["SHP"],
    emoji: "ðŸ‡¸ðŸ‡­",
    ioc: "",
    languages: ["eng"],
    name: "Saint Helena, Ascension And Tristan Da Cunha",
    status: "assigned",
  },
  {
    alpha2: "SI",
    alpha3: "SVN",
    countryCallingCodes: ["386"],
    currencies: ["EUR"],
    emoji: "ðŸ‡¸ðŸ‡®",
    ioc: "SLO",
    languages: ["slv"],
    name: "Slovenia",
    status: "assigned",
  },
  {
    alpha2: "SJ",
    alpha3: "SJM",
    countryCallingCodes: ["47"],
    currencies: ["NOK"],
    emoji: "ðŸ‡¸ðŸ‡¯",
    ioc: "",
    languages: [],
    name: "Svalbard And Jan Mayen",
    status: "assigned",
  },
  {
    alpha2: "SK",
    alpha3: "SVK",
    countryCallingCodes: ["421"],
    currencies: ["EUR"],
    emoji: "ðŸ‡¸ðŸ‡°",
    ioc: "SVK",
    languages: ["slk"],
    name: "Slovakia",
    status: "assigned",
  },
  {
    alpha2: "SK",
    alpha3: "SKM",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "Sikkim",
    status: "deleted",
  },
  {
    alpha2: "SL",
    alpha3: "SLE",
    countryCallingCodes: ["232"],
    currencies: ["SLL"],
    emoji: "ðŸ‡¸ðŸ‡±",
    ioc: "SLE",
    languages: ["eng"],
    name: "Sierra Leone",
    status: "assigned",
  },
  {
    alpha2: "SM",
    alpha3: "SMR",
    countryCallingCodes: ["378"],
    currencies: ["EUR"],
    emoji: "ðŸ‡¸ðŸ‡²",
    ioc: "SMR",
    languages: ["ita"],
    name: "San Marino",
    status: "assigned",
  },
  {
    alpha2: "SN",
    alpha3: "SEN",
    countryCallingCodes: ["221"],
    currencies: ["XOF"],
    emoji: "ðŸ‡¸ðŸ‡³",
    ioc: "SEN",
    languages: ["fra"],
    name: "Senegal",
    status: "assigned",
  },
  {
    alpha2: "SO",
    alpha3: "SOM",
    countryCallingCodes: ["252"],
    currencies: ["SOS"],
    emoji: "ðŸ‡¸ðŸ‡´",
    ioc: "SOM",
    languages: ["som"],
    name: "Somalia",
    status: "assigned",
  },
  {
    alpha2: "SR",
    alpha3: "SUR",
    countryCallingCodes: ["597"],
    currencies: ["SRD"],
    emoji: "ðŸ‡¸ðŸ‡·",
    ioc: "SUR",
    languages: ["nld"],
    name: "Suriname",
    status: "assigned",
  },
  {
    alpha2: "SS",
    alpha3: "SSD",
    countryCallingCodes: ["211"],
    currencies: ["SSP"],
    emoji: "ðŸ‡¸ðŸ‡¸",
    ioc: "SSD",
    languages: ["eng"],
    name: "South Sudan",
    status: "assigned",
  },
  {
    alpha2: "ST",
    alpha3: "STP",
    countryCallingCodes: ["239"],
    currencies: ["STD"],
    emoji: "ðŸ‡¸ðŸ‡¹",
    ioc: "STP",
    languages: ["por"],
    name: "Sao Tome and Principe",
    status: "assigned",
  },
  {
    alpha2: "SV",
    alpha3: "SLV",
    countryCallingCodes: ["503"],
    currencies: ["USD"],
    emoji: "ðŸ‡¸ðŸ‡»",
    ioc: "ESA",
    languages: ["spa"],
    name: "El Salvador",
    status: "assigned",
  },
  {
    alpha2: "SX",
    alpha3: "SXM",
    countryCallingCodes: ["1 721"],
    currencies: ["ANG"],
    emoji: "ðŸ‡¸ðŸ‡½",
    ioc: "",
    languages: ["nld"],
    name: "Sint Maarten",
    status: "assigned",
  },
  {
    alpha2: "SY",
    alpha3: "SYR",
    countryCallingCodes: ["963"],
    currencies: ["SYP"],
    emoji: "ðŸ‡¸ðŸ‡¾",
    ioc: "SYR",
    languages: ["ara"],
    name: "Syrian Arab Republic",
    status: "assigned",
  },
  {
    alpha2: "SZ",
    alpha3: "SWZ",
    countryCallingCodes: ["268"],
    currencies: ["SZL"],
    emoji: "ðŸ‡¸ðŸ‡¿",
    ioc: "SWZ",
    languages: ["eng", "ssw"],
    name: "Swaziland",
    status: "assigned",
  },
  {
    alpha2: "TC",
    alpha3: "TCA",
    countryCallingCodes: ["1 649"],
    currencies: ["USD"],
    emoji: "ðŸ‡¹ðŸ‡¨",
    ioc: "",
    languages: ["eng"],
    name: "Turks And Caicos Islands",
    status: "assigned",
  },
  {
    alpha2: "TD",
    alpha3: "TCD",
    countryCallingCodes: ["235"],
    currencies: ["XAF"],
    emoji: "ðŸ‡¹ðŸ‡©",
    ioc: "CHA",
    languages: ["ara", "fra"],
    name: "Chad",
    status: "assigned",
  },
  {
    alpha2: "TF",
    alpha3: "ATF",
    countryCallingCodes: [],
    currencies: ["EUR"],
    emoji: "ðŸ‡¹ðŸ‡«",
    ioc: "",
    languages: ["fra"],
    name: "French Southern Territories",
    status: "assigned",
  },
  {
    alpha2: "TG",
    alpha3: "TGO",
    countryCallingCodes: ["228"],
    currencies: ["XOF"],
    emoji: "ðŸ‡¹ðŸ‡¬",
    ioc: "TOG",
    languages: ["fra"],
    name: "Togo",
    status: "assigned",
  },
  {
    alpha2: "TH",
    alpha3: "THA",
    countryCallingCodes: ["66"],
    currencies: ["THB"],
    emoji: "ðŸ‡¹ðŸ‡­",
    ioc: "THA",
    languages: ["tha"],
    name: "Thailand",
    status: "assigned",
  },
  {
    alpha2: "TJ",
    alpha3: "TJK",
    countryCallingCodes: ["992"],
    currencies: ["TJS"],
    emoji: "ðŸ‡¹ðŸ‡¯",
    ioc: "TJK",
    languages: ["tgk", "rus"],
    name: "Tajikistan",
    status: "assigned",
  },
  {
    alpha2: "TK",
    alpha3: "TKL",
    countryCallingCodes: ["690"],
    currencies: ["NZD"],
    emoji: "ðŸ‡¹ðŸ‡°",
    ioc: "",
    languages: ["eng"],
    name: "Tokelau",
    status: "assigned",
  },
  {
    alpha2: "TL",
    alpha3: "TLS",
    countryCallingCodes: ["670"],
    currencies: ["USD"],
    emoji: "ðŸ‡¹ðŸ‡±",
    ioc: "TLS",
    languages: ["por"],
    name: "Timor-Leste, Democratic Republic of",
    status: "assigned",
  },
  {
    alpha2: "TM",
    alpha3: "TKM",
    countryCallingCodes: ["993"],
    currencies: ["TMT"],
    emoji: "ðŸ‡¹ðŸ‡²",
    ioc: "TKM",
    languages: ["tuk", "rus"],
    name: "Turkmenistan",
    status: "assigned",
  },
  {
    alpha2: "TN",
    alpha3: "TUN",
    countryCallingCodes: ["216"],
    currencies: ["TND"],
    emoji: "ðŸ‡¹ðŸ‡³",
    ioc: "TUN",
    languages: ["ara"],
    name: "Tunisia",
    status: "assigned",
  },
  {
    alpha2: "TO",
    alpha3: "TON",
    countryCallingCodes: ["676"],
    currencies: ["TOP"],
    emoji: "ðŸ‡¹ðŸ‡´",
    ioc: "TGA",
    languages: ["eng"],
    name: "Tonga",
    status: "assigned",
  },
  {
    alpha2: "TP",
    alpha3: "TMP",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "East Timor",
    status: "deleted",
  },
  {
    alpha2: "TR",
    alpha3: "TUR",
    countryCallingCodes: ["90"],
    currencies: ["TRY"],
    emoji: "ðŸ‡¹ðŸ‡·",
    ioc: "TUR",
    languages: ["tur"],
    name: "Turkey",
    status: "assigned",
  },
  {
    alpha2: "TT",
    alpha3: "TTO",
    countryCallingCodes: ["1 868"],
    currencies: ["TTD"],
    emoji: "ðŸ‡¹ðŸ‡¹",
    ioc: "TTO",
    languages: ["eng"],
    name: "Trinidad And Tobago",
    status: "assigned",
  },
  {
    alpha2: "TV",
    alpha3: "TUV",
    countryCallingCodes: ["688"],
    currencies: ["AUD"],
    emoji: "ðŸ‡¹ðŸ‡»",
    ioc: "TUV",
    languages: ["eng"],
    name: "Tuvalu",
    status: "assigned",
  },
  {
    alpha2: "TW",
    alpha3: "TWN",
    countryCallingCodes: ["886"],
    currencies: ["TWD"],
    emoji: "ðŸ‡¹ðŸ‡¼",
    ioc: "TPE",
    languages: ["zho"],
    name: "Taiwan",
    status: "assigned",
  },
  {
    alpha2: "TZ",
    alpha3: "TZA",
    countryCallingCodes: ["255"],
    currencies: ["TZS"],
    emoji: "ðŸ‡¹ðŸ‡¿",
    ioc: "TAN",
    languages: ["swa", "eng"],
    name: "Tanzania, United Republic Of",
    status: "assigned",
  },
  {
    alpha2: "UA",
    alpha3: "UKR",
    countryCallingCodes: ["380"],
    currencies: ["UAH"],
    emoji: "ðŸ‡ºðŸ‡¦",
    ioc: "UKR",
    languages: ["ukr", "rus"],
    name: "Ukraine",
    status: "assigned",
  },
  {
    alpha2: "UG",
    alpha3: "UGA",
    countryCallingCodes: ["256"],
    currencies: ["UGX"],
    emoji: "ðŸ‡ºðŸ‡¬",
    ioc: "UGA",
    languages: ["eng", "swa"],
    name: "Uganda",
    status: "assigned",
  },
  {
    alpha2: "UM",
    alpha3: "UMI",
    countryCallingCodes: ["1"],
    currencies: ["USD"],
    emoji: "ðŸ‡ºðŸ‡²",
    ioc: "",
    languages: ["eng"],
    name: "United States Minor Outlying Islands",
    status: "assigned",
  },
  {
    alpha2: "US",
    alpha3: "USA",
    countryCallingCodes: ["1"],
    currencies: ["USD"],
    emoji: "ðŸ‡ºðŸ‡¸",
    ioc: "USA",
    languages: ["eng"],
    name: "United States",
    status: "assigned",
  },
  {
    alpha2: "UY",
    alpha3: "URY",
    countryCallingCodes: ["598"],
    currencies: ["UYU", "UYI"],
    emoji: "ðŸ‡ºðŸ‡¾",
    ioc: "URU",
    languages: ["spa"],
    name: "Uruguay",
    status: "assigned",
  },
  {
    alpha2: "UZ",
    alpha3: "UZB",
    countryCallingCodes: ["998"],
    currencies: ["UZS"],
    emoji: "ðŸ‡ºðŸ‡¿",
    ioc: "UZB",
    languages: ["uzb", "rus"],
    name: "Uzbekistan",
    status: "assigned",
  },
  {
    alpha2: "VA",
    alpha3: "VAT",
    countryCallingCodes: ["379", "39"],
    currencies: ["EUR"],
    emoji: "ðŸ‡»ðŸ‡¦",
    ioc: "",
    languages: ["ita"],
    name: "Vatican City State",
    status: "assigned",
  },
  {
    alpha2: "VC",
    alpha3: "VCT",
    countryCallingCodes: ["1 784"],
    currencies: ["XCD"],
    emoji: "ðŸ‡»ðŸ‡¨",
    ioc: "VIN",
    languages: ["eng"],
    name: "Saint Vincent And The Grenadines",
    status: "assigned",
  },
  {
    alpha2: "VD",
    alpha3: "VDR",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "Viet-Nam, Democratic Republic of",
    status: "deleted",
  },
  {
    alpha2: "VE",
    alpha3: "VEN",
    countryCallingCodes: ["58"],
    currencies: ["VEF"],
    emoji: "ðŸ‡»ðŸ‡ª",
    ioc: "VEN",
    languages: ["spa"],
    name: "Venezuela, Bolivarian Republic Of",
    status: "assigned",
  },
  {
    alpha2: "VG",
    alpha3: "VGB",
    countryCallingCodes: ["1 284"],
    currencies: ["USD"],
    emoji: "ðŸ‡»ðŸ‡¬",
    ioc: "IVB",
    languages: ["eng"],
    name: "Virgin Islands (British)",
    status: "assigned",
  },
  {
    alpha2: "VI",
    alpha3: "VIR",
    countryCallingCodes: ["1 340"],
    currencies: ["USD"],
    emoji: "ðŸ‡»ðŸ‡®",
    ioc: "ISV",
    languages: ["eng"],
    name: "Virgin Islands (US)",
    status: "assigned",
  },
  {
    alpha2: "VN",
    alpha3: "VNM",
    countryCallingCodes: ["84"],
    currencies: ["VND"],
    emoji: "ðŸ‡»ðŸ‡³",
    ioc: "VIE",
    languages: ["vie"],
    name: "Viet Nam",
    status: "assigned",
  },
  {
    alpha2: "VU",
    alpha3: "VUT",
    countryCallingCodes: ["678"],
    currencies: ["VUV"],
    emoji: "ðŸ‡»ðŸ‡º",
    ioc: "VAN",
    languages: ["bis", "eng", "fra"],
    name: "Vanuatu",
    status: "assigned",
  },
  {
    alpha2: "WF",
    alpha3: "WLF",
    countryCallingCodes: ["681"],
    currencies: ["XPF"],
    emoji: "ðŸ‡¼ðŸ‡«",
    ioc: "",
    languages: ["fra"],
    name: "Wallis And Futuna",
    status: "assigned",
  },
  {
    alpha2: "WK",
    alpha3: "WAK",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "Wake Island",
    status: "deleted",
  },
  {
    alpha2: "WS",
    alpha3: "WSM",
    countryCallingCodes: ["685"],
    currencies: ["WST"],
    emoji: "ðŸ‡¼ðŸ‡¸",
    ioc: "SAM",
    languages: ["eng", "smo"],
    name: "Samoa",
    status: "assigned",
  },

  {
    alpha2: "YD",
    alpha3: "YMD",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "Yemen, Democratic",
    status: "deleted",
  },
  {
    alpha2: "YE",
    alpha3: "YEM",
    countryCallingCodes: ["967"],
    currencies: ["YER"],
    emoji: "ðŸ‡¾ðŸ‡ª",
    ioc: "YEM",
    languages: ["ara"],
    name: "Yemen",
    status: "assigned",
  },
  {
    alpha2: "YT",
    alpha3: "MYT",
    countryCallingCodes: ["262"],
    currencies: ["EUR"],
    emoji: "ðŸ‡¾ðŸ‡¹",
    ioc: "",
    languages: ["fra"],
    name: "Mayotte",
    status: "assigned",
  },
  {
    alpha2: "YU",
    alpha3: "YUG",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "Yugoslavia",
    status: "deleted",
  },
  {
    alpha2: "ZA",
    alpha3: "ZAF",
    countryCallingCodes: ["27"],
    currencies: ["ZAR"],
    emoji: "ðŸ‡¿ðŸ‡¦",
    ioc: "RSA",
    languages: ["afr", "eng", "nbl", "som", "tso", "ven", "xho", "zul"],
    name: "South Africa",
    status: "assigned",
  },
  {
    alpha2: "ZM",
    alpha3: "ZMB",
    countryCallingCodes: ["260"],
    currencies: ["ZMW"],
    emoji: "ðŸ‡¿ðŸ‡²",
    ioc: "ZAM",
    languages: ["eng"],
    name: "Zambia",
    status: "assigned",
  },
  {
    alpha2: "ZR",
    alpha3: "ZAR",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    name: "Zaire",
    status: "deleted",
  },
  {
    alpha2: "ZW",
    alpha3: "ZWE",
    countryCallingCodes: ["263"],
    currencies: ["USD", "ZAR", "BWP", "GBP", "EUR"],
    emoji: "ðŸ‡¿ðŸ‡¼",
    ioc: "ZIM",
    languages: ["eng", "sna", "nde"],
    name: "Zimbabwe",
    status: "assigned",
  },
];
export type LeadStageType =
  | "student_loan_new"
  | "student_loan_closed"
  | "student_loan_lost"
  | "student_loan_accepted"
  | "student_loan_application_submission"
  | "student_loan_preparation";
export const stageLabels: Record<LeadStageType, string> = {
  student_loan_new: "New",
  student_loan_preparation: "Documentation",
  student_loan_application_submission: "Application Submitted",
  student_loan_accepted: "Application Accepted",
  student_loan_closed: "Loan Sanctioned",
  student_loan_lost: "Application Rejected",
};
export const leadsStageOptions = [
  {
    value: "student_loan_new",
    label: stageLabels.student_loan_new,
  },
  {
    value: "student_loan_preparation",
    label: stageLabels.student_loan_preparation,
  },
  {
    value: "student_loan_application_submission",
    label: stageLabels.student_loan_application_submission,
  },
  {
    value: "student_loan_accepted",
    label: stageLabels.student_loan_accepted,
  },
  {
    value: "student_loan_closed",
    label: stageLabels.student_loan_closed,
  },
  {
    value: "student_loan_lost",
    label: stageLabels.student_loan_lost,
  },
];

export const destinationCountries = [
  "USA",
  "UK",
  "Canada",
  "Australia",
  "Ireland",
  "New Zealand",
  "France",
  "Dubai",
  "Germany",
  "Other",
];

export const destinationCountriesFlags = {
  "United States of America": flags.US,
  USA: flags.US,
  "United Kingdom": flags.GB,
  UK: flags.GB,
  Canada: flags.CA,
  Australia: flags.AU,
  Ireland: flags.IE,
  "New Zealand": flags.NZ,
  France: flags.FR,
  Dubai: flags.AE,
  Germany: flags.DE,
};

export const intakeOptions = [
  "Summer 2025",
  "Fall 2025",
  "Spring 2026",
  "Summer 2026",
  "Fall 2026",
];
export const payoutData = [
  {
    id: 1,
    studentName: " Student",
    partnerName: "Partner",
    lander: "HDFC",
    disbMonth: "Jan",
    disbAmount: "3000",
    payoutPercentage: "50%",
    payout: "3000",
    currency: "USD",
  },
  {
    id: 2,
    studentName: " Student2",
    partnerName: "Partner2",
    lander: "HDFC",
    disbMonth: "Jan",
    disbAmount: "3000",
    payoutPercentage: "50%",
    payout: "3000",
    currency: "INR",
  },
  {
    id: 3,
    studentName: " Student3",
    partnerName: "Partner3",
    lander: "IDFC",
    disbMonth: "Jan",
    disbAmount: "3000",
    payoutPercentage: "80%",
    payout: "3000",
    currency: "USD",
  },
];
export const partnersData = [
  {
    id: 1,
    name: "HDFC",
    city: "Delhi",
    country: "India",
    isActive: true,
    created_at: "02/02/24 00:00:00",
  },
  {
    id: 2,
    name: "IDFC",
    city: "Mumbai",
    country: "India",
    isActive: false,
    created_at: "02/02/24 00:00:00",
  },

  {
    id: 3,
    name: "Prodigy",
    city: "Goa",
    country: "India",
    isActive: true,
    created_at: "02/02/24 00:00:00",
  },
];
export const partnersUserData = [
  {
    id: 1,
    firstName: "Ram",
    lastName: "Kumar",
    phone: "+1 (000) 000-0000",
    email: "email@domain.com",
    country: "India",
    partner_name: "HDFC",
    isActive: true,
    last_login_at: "02/02/24 00:00:00",
    created_at: "02/02/24 00:00:00",
  },
  {
    id: 2,
    firstName: "FirstName",
    lastName: "LastName",
    phone: "+1 (000) 000-0000",
    email: "email@domain.com",
    country: "India",
    partner_name: "HDFC",
    isActive: false,
    last_login_at: "02/02/24 00:00:00",
    created_at: "02/02/24 00:00:00",
  },

  {
    id: 3,
    firstName: "FirstName",
    lastName: "LastName",
    phone: "+1 (000) 000-0000",
    email: "email@domain.com",
    country: "India",
    partner_name: "HDFC",
    isActive: true,
    last_login_at: "02/02/24 00:00:00",
    created_at: "02/02/24 00:00:00",
  },
];
export const timezoneToCountry = {
  "Africa/Abidjan": "CI",
  "Africa/Accra": "GH",
  "Africa/Addis_Ababa": "ET",
  "Africa/Algiers": "DZ",
  "Africa/Asmara": "ER",
  "Africa/Bamako": "ML",
  "Africa/Bangui": "CF",
  "Africa/Banjul": "GM",
  "Africa/Bissau": "GW",
  "Africa/Blantyre": "MW",
  "Africa/Brazzaville": "CG",
  "Africa/Bujumbura": "BI",
  "Africa/Cairo": "EG",
  "Africa/Casablanca": "MA",
  "Africa/Ceuta": "ES",
  "Africa/Conakry": "GN",
  "Africa/Dakar": "SN",
  "Africa/Dar_es_Salaam": "TZ",
  "Africa/Djibouti": "DJ",
  "Africa/Douala": "CM",
  "Africa/El_Aaiun": "EH",
  "Africa/Freetown": "SL",
  "Africa/Gaborone": "BW",
  "Africa/Harare": "ZW",
  "Africa/Johannesburg": "ZA",
  "Africa/Juba": "SS",
  "Africa/Kampala": "UG",
  "Africa/Khartoum": "SD",
  "Africa/Kigali": "RW",
  "Africa/Kinshasa": "CD",
  "Africa/Lagos": "NG",
  "Africa/Libreville": "GA",
  "Africa/Lome": "TG",
  "Africa/Luanda": "AO",
  "Africa/Lubumbashi": "CD",
  "Africa/Lusaka": "ZM",
  "Africa/Malabo": "GQ",
  "Africa/Maputo": "MZ",
  "Africa/Maseru": "LS",
  "Africa/Mbabane": "SZ",
  "Africa/Mogadishu": "SO",
  "Africa/Monrovia": "LR",
  "Africa/Nairobi": "KE",
  "Africa/Ndjamena": "TD",
  "Africa/Niamey": "NE",
  "Africa/Nouakchott": "MR",
  "Africa/Ouagadougou": "BF",
  "Africa/Porto-Novo": "BJ",
  "Africa/Sao_Tome": "ST",
  "Africa/Tripoli": "LY",
  "Africa/Tunis": "TN",
  "Africa/Windhoek": "NA",
  "America/Adak": "US",
  "America/Anchorage": "US",
  "America/Anguilla": "AI",
  "America/Antigua": "AG",
  "America/Araguaina": "BR",
  "America/Argentina/Buenos_Aires": "AR",
  "America/Argentina/Catamarca": "AR",
  "America/Argentina/Cordoba": "AR",
  "America/Argentina/Jujuy": "AR",
  "America/Argentina/La_Rioja": "AR",
  "America/Argentina/Mendoza": "AR",
  "America/Argentina/Rio_Gallegos": "AR",
  "America/Argentina/Salta": "AR",
  "America/Argentina/San_Juan": "AR",
  "America/Argentina/San_Luis": "AR",
  "America/Argentina/Tucuman": "AR",
  "America/Argentina/Ushuaia": "AR",
  "America/Aruba": "AW",
  "America/Asuncion": "PY",
  "America/Atikokan": "CA",
  "America/Bahia": "BR",
  "America/Bahia_Banderas": "MX",
  "America/Barbados": "BB",
  "America/Belem": "BR",
  "America/Belize": "BZ",
  "America/Blanc-Sablon": "CA",
  "America/Boa_Vista": "BR",
  "America/Bogota": "CO",
  "America/Boise": "US",
  "America/Cambridge_Bay": "CA",
  "America/Campo_Grande": "BR",
  "America/Cancun": "MX",
  "America/Caracas": "VE",
  "America/Cayenne": "GF",
  "America/Cayman": "KY",
  "America/Chicago": "US",
  "America/Chihuahua": "MX",
  "America/Costa_Rica": "CR",
  "America/Creston": "CA",
  "America/Cuiaba": "BR",
  "America/Curacao": "CW",
  "America/Danmarkshavn": "GL",
  "America/Dawson": "CA",
  "America/Dawson_Creek": "CA",
  "America/Denver": "US",
  "America/Detroit": "US",
  "America/Dominica": "DM",
  "America/Edmonton": "CA",
  "America/Eirunepe": "BR",
  "America/El_Salvador": "SV",
  "America/Fort_Nelson": "CA",
  "America/Fortaleza": "BR",
  "America/Glace_Bay": "CA",
  "America/Godthab": "GL",
  "America/Goose_Bay": "CA",
  "America/Grand_Turk": "TC",
  "America/Grenada": "GD",
  "America/Guadeloupe": "GP",
  "America/Guatemala": "GT",
  "America/Guayaquil": "EC",
  "America/Guyana": "GY",
  "America/Halifax": "CA",
  "America/Havana": "CU",
  "America/Hermosillo": "MX",
  "America/Indiana/Indianapolis": "US",
  "America/Indiana/Knox": "US",
  "America/Indiana/Marengo": "US",
  "America/Indiana/Petersburg": "US",
  "America/Indiana/Tell_City": "US",
  "America/Indiana/Vevay": "US",
  "America/Indiana/Vincennes": "US",
  "America/Indiana/Winamac": "US",
  "America/Inuvik": "CA",
  "America/Iqaluit": "CA",
  "America/Jamaica": "JM",
  "America/Juneau": "US",
  "America/Kentucky/Louisville": "US",
  "America/Kentucky/Monticello": "US",
  "America/Kralendijk": "BQ",
  "America/La_Paz": "BO",
  "America/Lima": "PE",
  "America/Los_Angeles": "US",
  "America/Lower_Princes": "SX",
  "America/Maceio": "BR",
  "America/Managua": "NI",
  "America/Manaus": "BR",
  "America/Marigot": "MF",
  "America/Martinique": "MQ",
  "America/Matamoros": "MX",
  "America/Mazatlan": "MX",
  "America/Menominee": "US",
  "America/Merida": "MX",
  "America/Metlakatla": "US",
  "America/Mexico_City": "MX",
  "America/Miquelon": "PM",
  "America/Moncton": "CA",
  "America/Monterrey": "MX",
  "America/Montevideo": "UY",
  "America/Montserrat": "MS",
  "America/Nassau": "BS",
  "America/New_York": "US",
  "America/Nipigon": "CA",
  "America/Nome": "US",
  "America/Noronha": "BR",
  "America/North_Dakota/Beulah": "US",
  "America/North_Dakota/Center": "US",
  "America/North_Dakota/New_Salem": "US",
  "America/Nuuk": "GL",
  "America/Ojinaga": "MX",
  "America/Panama": "PA",
  "America/Pangnirtung": "CA",
  "America/Paramaribo": "SR",
  "America/Phoenix": "US",
  "America/Port-au-Prince": "HT",
  "America/Port_of_Spain": "TT",
  "America/Porto_Velho": "BR",
  "America/Puerto_Rico": "PR",
  "America/Punta_Arenas": "CL",
  "America/Rainy_River": "CA",
  "America/Rankin_Inlet": "CA",
  "America/Recife": "BR",
  "America/Regina": "CA",
  "America/Resolute": "CA",
  "America/Rio_Branco": "BR",
  "America/Santarem": "BR",
  "America/Santiago": "CL",
  "America/Santo_Domingo": "DO",
  "America/Sao_Paulo": "BR",
  "America/Scoresbysund": "GL",
  "America/Sitka": "US",
  "America/St_Barthelemy": "BL",
  "America/St_Johns": "CA",
  "America/St_Kitts": "KN",
  "America/St_Lucia": "LC",
  "America/St_Thomas": "VI",
  "America/St_Vincent": "VC",
  "America/Swift_Current": "CA",
  "America/Tegucigalpa": "HN",
  "America/Thule": "GL",
  "America/Thunder_Bay": "CA",
  "America/Tijuana": "MX",
  "America/Toronto": "CA",
  "America/Tortola": "VG",
  "America/Vancouver": "CA",
  "America/Whitehorse": "CA",
  "America/Winnipeg": "CA",
  "America/Yakutat": "US",
  "America/Yellowknife": "CA",
  "Antarctica/Casey": "AQ",
  "Antarctica/Davis": "AQ",
  "Antarctica/DumontDUrville": "AQ",
  "Antarctica/Macquarie": "AU",
  "Antarctica/Mawson": "AQ",
  "Antarctica/McMurdo": "AQ",
  "Antarctica/Palmer": "AQ",
  "Antarctica/Rothera": "AQ",
  "Antarctica/Syowa": "AQ",
  "Antarctica/Troll": "AQ",
  "Antarctica/Vostok": "AQ",
  "Arctic/Longyearbyen": "SJ",
  "Asia/Aden": "YE",
  "Asia/Almaty": "KZ",
  "Asia/Amman": "JO",
  "Asia/Anadyr": "RU",
  "Asia/Aqtau": "KZ",
  "Asia/Aqtobe": "KZ",
  "Asia/Ashgabat": "TM",
  "Asia/Ashkhabad": "TM", // deprecated
  "Asia/Atyrau": "KZ",
  "Asia/Baghdad": "IQ",
  "Asia/Bahrain": "BH",
  "Asia/Baku": "AZ",
  "Asia/Bangkok": "TH",
  "Asia/Barnaul": "RU",
  "Asia/Beirut": "LB",
  "Asia/Bishkek": "KG",
  "Asia/Brunei": "BN",
  "Asia/Calcutta": "IN", // deprecated
  "Asia/Chita": "RU",
  "Asia/Choibalsan": "MN",
  "Asia/Colombo": "LK",
  "Asia/Dacca": "BD", // deprecated
  "Asia/Damascus": "SY",
  "Asia/Dhaka": "BD",
  "Asia/Dili": "TL",
  "Asia/Dubai": "AE",
  "Asia/Dushanbe": "TJ",
  "Asia/Famagusta": "CY",
  "Asia/Gaza": "PS",
  "Asia/Hebron": "PS",
  "Asia/Ho_Chi_Minh": "VN",
  "Asia/Hong_Kong": "HK",
  "Asia/Hovd": "MN",
  "Asia/Irkutsk": "RU",
  "Asia/Istanbul": "TR", // deprecated
  "Asia/Jakarta": "ID",
  "Asia/Jayapura": "ID",
  "Asia/Jerusalem": "IL",
  "Asia/Kabul": "AF",
  "Asia/Kamchatka": "RU",
  "Asia/Karachi": "PK",
  "Asia/Kashgar": "CN", // deprecated
  "Asia/Kathmandu": "NP",
  "Asia/Katmandu": "NP", // deprecated
  "Asia/Khandyga": "RU",
  "Asia/Kolkata": "IN",
  "Asia/Krasnoyarsk": "RU",
  "Asia/Kuala_Lumpur": "MY",
  "Asia/Kuching": "MY",
  "Asia/Kuwait": "KW",
  "Asia/Macau": "MO",
  "Asia/Magadan": "RU",
  "Asia/Makassar": "ID",
  "Asia/Manila": "PH",
  "Asia/Muscat": "OM",
  "Asia/Nicosia": "CY",
  "Asia/Novokuznetsk": "RU",
  "Asia/Novosibirsk": "RU",
  "Asia/Omsk": "RU",
  "Asia/Oral": "KZ",
  "Asia/Phnom_Penh": "KH",
  "Asia/Pontianak": "ID",
  "Asia/Pyongyang": "KP",
  "Asia/Qatar": "QA",
  "Asia/Qostanay": "KZ",
  "Asia/Qyzylorda": "KZ",
  "Asia/Rangoon": "MM", // deprecated
  "Asia/Riyadh": "SA",
  "Asia/Saigon": "VN", // deprecated
  "Asia/Sakhalin": "RU",
  "Asia/Samarkand": "UZ",
  "Asia/Seoul": "KR",
  "Asia/Shanghai": "CN",
  "Asia/Singapore": "SG",
  "Asia/Srednekolymsk": "RU",
  "Asia/Taipei": "TW",
  "Asia/Tashkent": "UZ",
  "Asia/Tbilisi": "GE",
  "Asia/Tehran": "IR",
  "Asia/Tel_Aviv": "IL", // deprecated
  "Asia/Thimbu": "BT", // deprecated
  "Asia/Thimphu": "BT",
  "Asia/Tokyo": "JP",
  "Asia/Tomsk": "RU",
  "Asia/Ujung_Pandang": "ID", // deprecated
  "Asia/Ulaanbaatar": "MN",
  "Asia/Ulan_Bator": "MN", // deprecated
  "Asia/Urumqi": "CN",
  "Asia/Ust-Nera": "RU",
  "Asia/Vientiane": "LA",
  "Asia/Vladivostok": "RU",
  "Asia/Yakutsk": "RU",
  "Asia/Yangon": "MM",
  "Asia/Yekaterinburg": "RU",
  "Asia/Yerevan": "AM",
  "Atlantic/Azores": "PT",
  "Atlantic/Bermuda": "BM",
  "Atlantic/Canary": "ES",
  "Atlantic/Cape_Verde": "CV",
  "Atlantic/Faroe": "FO",
  "Atlantic/Madeira": "PT",
  "Atlantic/Reykjavik": "IS",
  "Atlantic/South_Georgia": "GS",
  "Atlantic/St_Helena": "SH",
  "Atlantic/Stanley": "FK",
  "Australia/Adelaide": "AU",
  "Australia/Brisbane": "AU",
  "Australia/Broken_Hill": "AU",
  "Australia/Currie": "AU",
  "Australia/Darwin": "AU",
  "Australia/Eucla": "AU",
  "Australia/Hobart": "AU",
  "Australia/LHI": "AU", // deprecated
  "Australia/Lindeman": "AU",
  "Australia/Lord_Howe": "AU",
  "Australia/Melbourne": "AU",
  "Australia/NSW": "AU", // deprecated
  "Australia/North": "AU", // deprecated
  "Australia/Perth": "AU",
  "Australia/Queensland": "AU", // deprecated
  "Australia/South": "AU", // deprecated
  "Australia/Sydney": "AU",
  "Australia/Tasmania": "AU", // deprecated
  "Australia/Victoria": "AU", // deprecated
  "Australia/West": "AU", // deprecated
  "Australia/Yancowinna": "AU", // deprecated
  "Brazil/Acre": "BR", // deprecated
  "Brazil/DeNoronha": "BR", // deprecated
  "Brazil/East": "BR", // deprecated
  "Brazil/West": "BR", // deprecated
  "Canada/Atlantic": "CA", // deprecated
  "Canada/Central": "CA", // deprecated
  "Canada/Eastern": "CA", // deprecated
  "Canada/Mountain": "CA", // deprecated
  "Canada/Newfoundland": "CA", // deprecated
  "Canada/Pacific": "CA", // deprecated
  "Canada/Saskatchewan": "CA", // deprecated
  "Canada/Yukon": "CA", // deprecated
  "Chile/Continental": "CL", // deprecated
  "Chile/EasterIsland": "CL", // deprecated
  Cuba: "CU", // deprecated
  Egypt: "EG", // deprecated
  Eire: "IE", // deprecated
  "Europe/Amsterdam": "NL",
  "Europe/Andorra": "AD",
  "Europe/Astrakhan": "RU",
  "Europe/Athens": "GR",
  "Europe/Belfast": "GB", // deprecated
  "Europe/Belgrade": "RS",
  "Europe/Berlin": "DE",
  "Europe/Bratislava": "SK",
  "Europe/Brussels": "BE",
  "Europe/Bucharest": "RO",
  "Europe/Budapest": "HU",
  "Europe/Busingen": "DE",
  "Europe/Chisinau": "MD",
  "Europe/Copenhagen": "DK",
  "Europe/Dublin": "IE",
  "Europe/Gibraltar": "GI",
  "Europe/Guernsey": "GG",
  "Europe/Helsinki": "FI",
  "Europe/Isle_of_Man": "IM",
  "Europe/Istanbul": "TR",
  "Europe/Jersey": "JE",
  "Europe/Kaliningrad": "RU",
  "Europe/Kiev": "UA",
  "Europe/Kirov": "RU",
  "Europe/Lisbon": "PT",
  "Europe/Ljubljana": "SI",
  "Europe/London": "GB",
  "Europe/Luxembourg": "LU",
  "Europe/Madrid": "ES",
  "Europe/Malta": "MT",
  "Europe/Mariehamn": "AX",
  "Europe/Minsk": "BY",
  "Europe/Monaco": "MC",
  "Europe/Moscow": "RU",
  "Europe/Oslo": "NO",
  "Europe/Paris": "FR",
  "Europe/Podgorica": "ME",
  "Europe/Prague": "CZ",
  "Europe/Riga": "LV",
  "Europe/Rome": "IT",
  "Europe/Samara": "RU",
  "Europe/San_Marino": "SM",
  "Europe/Sarajevo": "BA",
  "Europe/Saratov": "RU",
  "Europe/Simferopol": "UA", // deprecated
  "Europe/Skopje": "MK",
  "Europe/Sofia": "BG",
  "Europe/Stockholm": "SE",
  "Europe/Tallinn": "EE",
  "Europe/Tirane": "AL",
  "Europe/Tiraspol": "MD", // deprecated
  "Europe/Ulyanovsk": "RU",
  "Europe/Uzhgorod": "UA",
  "Europe/Vaduz": "LI",
  "Europe/Vatican": "VA",
  "Europe/Vienna": "AT",
  "Europe/Vilnius": "LT",
  "Europe/Volgograd": "RU",
  "Europe/Warsaw": "PL",
  "Europe/Zagreb": "HR",
  "Europe/Zaporozhye": "UA",
  "Europe/Zurich": "CH",
  GB: "GB", // deprecated
  "GB-Eire": "GB", // deprecated
  Greenwich: "GB", // deprecated
  Hongkong: "HK", // deprecated
  Iceland: "IS", // deprecated
  "Indian/Antananarivo": "MG",
  "Indian/Chagos": "IO",
  "Indian/Christmas": "CX",
  "Indian/Cocos": "CC",
  "Indian/Comoro": "KM",
  "Indian/Kerguelen": "TF",
  "Indian/Mahe": "SC",
  "Indian/Maldives": "MV",
  "Indian/Mauritius": "MU",
  "Indian/Mayotte": "YT",
  "Indian/Reunion": "RE",
  Iran: "IR", // deprecated
  Israel: "IL", // deprecated
  Jamaica: "JM", // deprecated
  Japan: "JP", // deprecated
  Kwajalein: "MH", // deprecated
  Libya: "LY", // deprecated
  MET: "DE", // deprecated
  MST7MDT: "US", // deprecated
  "Mexico/BajaNorte": "MX", // deprecated
  "Mexico/BajaSur": "MX", // deprecated
  "Mexico/General": "MX", // deprecated
  NZ: "NZ", // deprecated
  "NZ-CHAT": "NZ", // deprecated
  Navajo: "US", // deprecated
  PRC: "CN", // deprecated
  "Pacific/Apia": "WS",
  "Pacific/Auckland": "NZ",
  "Pacific/Bougainville": "PG",
  "Pacific/Chatham": "NZ",
  "Pacific/Chuuk": "FM",
  "Pacific/Easter": "CL",
  "Pacific/Efate": "VU",
  "Pacific/Enderbury": "KI",
  "Pacific/Fakaofo": "TK",
  "Pacific/Fiji": "FJ",
  "Pacific/Funafuti": "TV",
  "Pacific/Galapagos": "EC",
  "Pacific/Gambier": "PF",
  "Pacific/Guadalcanal": "SB",
  "Pacific/Guam": "GU",
  "Pacific/Honolulu": "US",
  "Pacific/Johnston": "US", // deprecated
  "Pacific/Kanton": "KI",
  "Pacific/Kiritimati": "KI",
  "Pacific/Kosrae": "FM",
  "Pacific/Kwajalein": "MH",
  "Pacific/Majuro": "MH",
  "Pacific/Marquesas": "PF",
  "Pacific/Midway": "UM",
  "Pacific/Nauru": "NR",
  "Pacific/Niue": "NU",
  "Pacific/Norfolk": "NF",
  "Pacific/Noumea": "NC",
  "Pacific/Pago_Pago": "AS",
  "Pacific/Palau": "PW",
  "Pacific/Pitcairn": "PN",
  "Pacific/Pohnpei": "FM",
  "Pacific/Ponape": "FM", // deprecated
  "Pacific/Port_Moresby": "PG",
  "Pacific/Rarotonga": "CK",
  "Pacific/Saipan": "MP",
  "Pacific/Samoa": "WS", // deprecated
  "Pacific/Tahiti": "PF",
  "Pacific/Tarawa": "KI",
  "Pacific/Tongatapu": "TO",
  "Pacific/Truk": "FM", // deprecated
  "Pacific/Wake": "UM",
  "Pacific/Wallis": "WF",
  "Pacific/Yap": "FM",
  Poland: "PL", // deprecated
  Portugal: "PT", // deprecated
  ROC: "TW", // deprecated
  ROK: "KR", // deprecated
  Singapore: "SG", // deprecated
  Turkey: "TR", // deprecated
  UCT: "GB", // deprecated
  "US/Alaska": "US", // deprecated
  "US/Aleutian": "US", // deprecated
  "US/Arizona": "US", // deprecated
  "US/Central": "US", // deprecated
  "US/East-Indiana": "US", // deprecated
  "US/Eastern": "US", // deprecated
  "US/Hawaii": "US", // deprecated
  "US/Indiana-Starke": "US", // deprecated
  "US/Michigan": "US", // deprecated
  "US/Mountain": "US", // deprecated
  "US/Pacific": "US", // deprecated
  "US/Pacific-New": "US", // deprecated
  "US/Samoa": "AS", // deprecated
  UTC: "GB",
  Universal: "GB", // deprecated
  "W-SU": "RU", // deprecated
  WET: "PT", // deprecated
  Zulu: "GB", // deprecated
};

export const IndianStates = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Odisha",
];
export const IndianStatesData = [
  { name: "Andaman and Nicobar Islands", code: "AN" },
  { name: "Andhra Pradesh", code: "AP" },
  { name: "Arunachal Pradesh", code: "AR" },
  { name: "Assam", code: "AS" },
  { name: "Bihar", code: "BR" },
  { name: "Chandigarh", code: "CH" },
  { name: "Chhattisgarh", code: "CT" },
  { name: "Dadra and Nagar Haveli and Daman and Diu", code: "DN" },
  { name: "Delhi", code: "DL" },
  { name: "Goa", code: "GA" },
  { name: "Gujarat", code: "GJ" },
  { name: "Haryana", code: "HR" },
  { name: "Himachal Pradesh", code: "HP" },
  { name: "Jammu and Kashmir", code: "JK" },
  { name: "Jharkhand", code: "JH" },
  { name: "Karnataka", code: "KA" },
  { name: "Kerala", code: "KL" },
  { name: "Ladakh", code: "LA" },
  { name: "Lakshadweep", code: "LD" },
  { name: "Madhya Pradesh", code: "MP" },
  { name: "Maharashtra", code: "MH" },
  { name: "Manipur", code: "MN" },
  { name: "Meghalaya", code: "ML" },
  { name: "Mizoram", code: "MZ" },
  { name: "Nagaland", code: "NL" },
  { name: "Odisha", code: "OR" },
  { name: "Puducherry", code: "PY" },
  { name: "Punjab", code: "PB" },
  { name: "Rajasthan", code: "RJ" },
  { name: "Sikkim", code: "SK" },
  { name: "Tamil Nadu", code: "TN" },
  { name: "Telangana", code: "TG" },
  { name: "Tripura", code: "TR" },
  { name: "Uttar Pradesh", code: "UP" },
  { name: "Uttarakhand", code: "UT" },
  { name: "West Bengal", code: "WB" },
  { name: "Odisha", code: "OR" },
  { name: "Telangana", code: "TG" },
  { name: "Uttar Pradesh", code: "UP" },
  { name: "Uttarakhand", code: "UT" },
  { name: "West Bengal", code: "WB" },
];
